// Generate NFC additions from the pinned Colibri Unicode16 table, reusing the
// existing NFD backing. See NFC.md for source identity, license and acceptance.
// Run from the repository root:
// go run ./internal/tokenizer/gennfc -source /path/to/qwen38_nfc_tables.h
package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"maps"
	"os"
	"regexp"
	"slices"
	"strconv"
	"strings"
)

func main() {
	source := flag.String("source", "", "pinned Colibri c/qwen38_nfc_tables.h")
	flag.Parse()
	raw, err := os.ReadFile(*source)
	check(err)
	const sourceSHA = "ae7f710fc7169e7b4f8798124fda348fc829e73aa184d8820489b2e38b0de340"
	if fmt.Sprintf("%x", sha256.Sum256(raw)) != sourceSHA {
		panic("NFC source differs from pinned Colibri f028d26b table")
	}
	section := func(name string) string {
		_, tail, ok := strings.Cut(string(raw), name+"[")
		if !ok {
			panic("missing table " + name)
		}
		_, tail, _ = strings.Cut(tail, "{")
		result, _, _ := strings.Cut(tail, "};")
		return result
	}
	var values []rune
	for _, value := range regexp.MustCompile(`0x[0-9a-f]+`).FindAllString(section("q38_nfc_decomp_values"), -1) {
		values = append(values, number(value))
	}
	decompositions := map[rune][]rune{}
	for _, row := range regexp.MustCompile(`\{(0x[0-9a-f]+), ([0-9]+), ([0-9]+)\}`).FindAllStringSubmatch(section("q38_nfc_decomp"), -1) {
		key, offset, length := number(row[1]), number(row[2]), number(row[3])
		decompositions[key] = slices.Clone(values[offset : offset+length])
	}
	var expand func(rune, map[rune]bool) []rune
	expand = func(key rune, active map[rune]bool) []rune {
		children, found := decompositions[key]
		if !found {
			return []rune{key}
		}
		if active[key] {
			panic("decomposition cycle")
		}
		active[key] = true
		var result []rune
		for _, child := range children {
			result = append(result, expand(child, active)...)
		}
		delete(active, key)
		return result
	}
	current := map[rune][]rune{}
	for key := range decompositions {
		current[key] = expand(key, map[rune]bool{})
	}
	old := existingNFD()
	for key, prior := range old {
		if !slices.Equal(prior, current[key]) {
			panic(fmt.Sprintf("existing WPM NFD decomposition differs at %U", key))
		}
		delete(current, key)
	}
	var output bytes.Buffer
	fmt.Fprintf(&output, "// Code generated by gennfc; DO NOT EDIT.\n// Colibri f028d26b422144ed4a69ad9aeaee2553ce0f9572, Unicode 16.0.0.\n// Source SHA256 %s. See NFC.md and ../../licenses.\n\npackage tokenizer\n\n", sourceSHA)
	fmt.Fprintln(&output, "// Additional recursive decompositions; nfdTable remains unchanged for WPM.\nvar nfcDecompositionDelta = map[rune][]rune{")
	for _, key := range slices.Sorted(maps.Keys(current)) {
		fmt.Fprintf(&output, "0x%X: {", key)
		for _, value := range current[key] {
			fmt.Fprintf(&output, "0x%X,", value)
		}
		fmt.Fprintln(&output, "},")
	}
	fmt.Fprintln(&output, "}\n\nvar nfcCombiningClass = map[rune]uint8{")
	ccc := regexp.MustCompile(`\{(0x[0-9a-f]+), ([0-9]+)\}`).FindAllStringSubmatch(section("q38_nfc_ccc"), -1)
	for _, row := range ccc {
		fmt.Fprintf(&output, "%s: %s,\n", row[1], row[2])
	}
	fmt.Fprintln(&output, "}\n\nvar nfcComposition = map[[2]rune]rune{")
	compositionCount := 0
	for _, row := range regexp.MustCompile(`\{(0x[0-9a-f]+), (0x[0-9a-f]+), (0x[0-9a-f]+)\}`).FindAllStringSubmatch(section("q38_nfc_compose"), -1) {
		// Unicode 16 section 3.12: Hangul syllables compose algorithmically.
		if composite := number(row[3]); composite >= 0xAC00 && composite <= 0xD7A3 {
			continue
		}
		fmt.Fprintf(&output, "{%s,%s}: %s,\n", row[1], row[2], row[3])
		compositionCount++
	}
	fmt.Fprintln(&output, "}")
	encoded, err := format.Source(output.Bytes())
	check(err)
	check(os.WriteFile("internal/tokenizer/nfc_table.go", encoded, 0644))
	fmt.Printf("NFC generated: reused=%d delta=%d ccc=%d non-Hangul composition=%d\n", len(old), len(current), len(ccc), compositionCount)
}

func number(value string) rune {
	n, err := strconv.ParseInt(value, 0, 32)
	check(err)
	return rune(n)
}

func existingNFD() map[rune][]rune {
	file, err := parser.ParseFile(token.NewFileSet(), "internal/tokenizer/nfd_table.go", nil, 0)
	check(err)
	result := map[rune][]rune{}
	ast.Inspect(file, func(node ast.Node) bool {
		value, ok := node.(*ast.ValueSpec)
		if !ok || len(value.Names) != 1 || value.Names[0].Name != "nfdTable" {
			return true
		}
		for _, entry := range value.Values[0].(*ast.CompositeLit).Elts {
			pair := entry.(*ast.KeyValueExpr)
			key := number(pair.Key.(*ast.BasicLit).Value)
			for _, child := range pair.Value.(*ast.CompositeLit).Elts {
				result[key] = append(result[key], number(child.(*ast.BasicLit).Value))
			}
		}
		return false
	})
	if len(result) == 0 {
		panic("existing NFD table not found")
	}
	return result
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
