//go:build ignore

// Generator for nfd_parity_fixtures_test.go. Uses golang.org/x/text to compute
// the reference: strip(norm.NFD.String(s)) where strip removes category-M runes
// (mirroring preprocessWPM's mark-stripping). The committed parity test then
// checks strip(nfdString(s)) == these fixtures with NO x/text dependency.
//
//	go run gen_nfd_parity_fixtures.go   # writes nfd_parity_fixtures_test.go
package main

import (
	"bufio"
	"fmt"
	"os"
	"unicode"

	"golang.org/x/text/unicode/norm"
)

func strip(s string) string {
	out := make([]rune, 0, len(s))
	for _, r := range s {
		if unicode.Is(unicode.M, r) {
			continue
		}
		out = append(out, r)
	}
	return string(out)
}

func main() {
	var corpus []string
	add := func(ss ...string) { corpus = append(corpus, ss...) }

	// ASCII / plain
	add("", "hello world", "The quick brown fox.", "a", " ", "\t\n")
	// Precomposed accented Latin (NFC forms)
	add("café", "naïve", "résumé", "Zürich", "Ångström", "señor", "façade",
		"Grüße", "coöperate", "El Niño", "jalapeño", "Dvořák", "Škoda",
		"Đà Nẵng", "Việt Nam", "Nguyễn", "Łódź", "Bjørn")
	// Combining-sequence (decomposed) inputs and mixed
	add("é", "à́", "ọ̈", "ḍ̇", "Å")
	// Full range of Latin-1 supplement + Latin Extended-A precomposed letters
	for r := rune(0x00C0); r <= 0x024F; r++ {
		corpus = append(corpus, string(r))
	}
	// Combining diacritical marks alone and after base
	for r := rune(0x0300); r <= 0x036F; r++ {
		corpus = append(corpus, "x"+string(r), string(r))
	}
	// Hangul syllables (algorithmic decomposition) — sample across the block
	for r := rune(0xAC00); r <= 0xD7A3; r += 37 {
		corpus = append(corpus, string(r))
	}
	add("한국어", "안녕하세요", "훈민정음", "김치")
	// CJK (no decomposition) and CJK compatibility ideographs (which do decompose)
	add("你好世界", "漢字", "日本語", "中文")
	for r := rune(0xF900); r <= 0xFAFF; r += 11 {
		corpus = append(corpus, string(r))
	}
	// Greek/Cyrillic precomposed with accents
	add("Ελληνικά", "άέίόύ", "ΐΰ", "Ѐ", "Ѝ", "й", "Й")
	// Emoji and symbols (no decomposition)
	add("😀", "👍🏽", "🇺🇸", "café☕", "→∞≠", "①②③")
	// Circled/compat symbols that decompose under NFKD but NOT NFD (must stay put)
	add("ﬁ", "½", "²", "Ⅷ")
	// Long mixed string
	add("Voilà! Crème brûlée at the café — naïve résumé, Zürich, señor Muñoz.")

	f, err := os.Create("nfd_parity_fixtures_test.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	w := bufio.NewWriter(f)
	defer w.Flush()

	fmt.Fprint(w, `// Code generated by gen_nfd_parity_fixtures.go; DO NOT EDIT.
// Reference outputs = strip(norm.NFD.String(s)) from golang.org/x/text.
// Regenerate with: go run gen_nfd_parity_fixtures.go (requires x/text).

package tokenizer

// nfdParityCases is a broad Unicode corpus with the golden strip(NFD(s)) result
// computed by golang.org/x/text at generation time.
var nfdParityCases = []struct {
	in   string
	want string // strip(norm.NFD.String(in)), marks removed
}{
`)
	for _, s := range corpus {
		fmt.Fprintf(w, "\t{in: %q, want: %q},\n", s, strip(norm.NFD.String(s)))
	}
	fmt.Fprint(w, "}\n")

	fmt.Fprintf(os.Stderr, "generated nfd_parity_fixtures_test.go with %d cases\n", len(corpus))
}
