//go:build ignore

// Generator for nfd_table.go — the committed canonical-decomposition table is
// the source of truth. Regenerating requires temporarily re-adding
// golang.org/x/text (this file's only dependency); the committed table is
// stdlib-only at runtime.
//
// For each rune r in [0, 0x10FFFF] it computes norm.NFD.String(string(r)); if
// that differs from string(r), r has a canonical decomposition. Per-rune NFD is
// exactly the recursive canonical decomposition of r (canonical ordering of a
// single starting rune plus its marks is irrelevant here — see nfd.go).
//
//	go run gen_nfd_table.go   # writes nfd_table.go
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"

	"golang.org/x/text/unicode/norm"
)

func main() {
	type entry struct {
		r  rune
		to []rune
	}
	var entries []entry
	for r := rune(0); r <= 0x10FFFF; r++ {
		if r >= 0xD800 && r <= 0xDFFF { // surrogates: not valid scalar values
			continue
		}
		s := string(r)
		d := norm.NFD.String(s)
		if d == s {
			continue
		}
		entries = append(entries, entry{r: r, to: []rune(d)})
	}

	var w bytes.Buffer

	fmt.Fprint(&w, `// Code generated by gen_nfd_table.go; DO NOT EDIT.
// Regenerate with: go run gen_nfd_table.go (requires golang.org/x/text).
// Canonical (NFD, not NFKD) recursive per-rune decompositions. See nfd.go.

package tokenizer

// nfdTable maps a rune to its fully-expanded recursive canonical decomposition.
// Runes absent from the table decompose to themselves.
var nfdTable = map[rune][]rune{
`)
	for _, e := range entries {
		fmt.Fprintf(&w, "\t0x%04X: {", e.r)
		for i, c := range e.to {
			if i > 0 {
				fmt.Fprint(&w, ", ")
			}
			fmt.Fprintf(&w, "0x%04X", c)
		}
		fmt.Fprint(&w, "},\n")
	}
	fmt.Fprint(&w, "}\n")

	src, err := format.Source(w.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("nfd_table.go", src, 0o644); err != nil {
		panic(err)
	}

	fmt.Fprintf(os.Stderr, "generated nfd_table.go with %d entries\n", len(entries))
}
