package media

import (
	"context"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"fmt"
	"math"
	"slices"
	"testing"

	"overgo/internal/binaryschema"
	"overgo/internal/recipecontract"
)

// Generated by libsndfile 1.2.2 / libFLAC 1.4.3: 24 stereo PCM16 frames,
// repeating (0,.5), (-.5,.25), (.125,-.125), at 16 kHz. No corpus bytes.
const stereoFLACHex = "664c6143000000221000100000002300002303e802f0000000181296d673083f5a9f3a5be1fc92a2ef1784000028200000007265666572656e6365206c6962464c414320312e342e3320323032333036323300000000fff865a80017d8110010002c2c2c2c2c2c2c2c4400200b34cd334cd334cd334cd0fb4b"

func TestAudioDecodeWAVEncodings(t *testing.T) {
	for _, test := range []struct {
		name        string
		codec, bits uint16
		payload     []byte
		want        []float32
	}{
		{"pcm8", 1, 8, []byte{0, 128, 192, 255}, []float32{-1, 0, .5, 127.0 / 128}},
		{"pcm16", 1, 16, []byte{0, 128, 0, 0, 0, 64, 255, 127}, []float32{-1, 0, .5, 32767.0 / 32768}},
		{"pcm24", 1, 24, []byte{0, 0, 128, 0, 0, 0, 0, 0, 64, 255, 255, 127}, []float32{-1, 0, .5, 8388607.0 / 8388608}},
		{"pcm32", 1, 32, []byte{0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 64, 255, 255, 255, 127}, []float32{-1, 0, .5, 1}},
		{"float32", 3, 32, binaryschema.LittleEndian.Float32s([]float32{-1, 0, .5, 2}), []float32{-1, 0, .5, 2}},
		{"float64", 3, 64, binary.LittleEndian.AppendUint64(binary.LittleEndian.AppendUint64(nil, math.Float64bits(-.5)), math.Float64bits(.25)), []float32{-.5, .25}},
	} {
		t.Run(test.name, func(t *testing.T) {
			audio, status, err := DecodeAudio(t.Context(), wavFixture(test.codec, test.bits, 2, test.payload), uint64(len(test.want)))
			if err != nil || status != recipecontract.AudioDecodeComplete || audio.Format.Channels != 2 || audio.Format.SampleRate != 16000 || !slices.Equal(audio.Samples, test.want) {
				t.Fatalf("decode=%+v status=%s error=%v want=%v", audio, status, err, test.want)
			}
		})
	}
	// An unknown odd-sized chunk consumes its alignment byte.
	wave := wavFixture(1, 16, 1, []byte{0, 64})
	wave = append(wave[:12], append([]byte{'J', 'U', 'N', 'K', 1, 0, 0, 0, 42, 0}, wave[12:]...)...)
	binary.LittleEndian.PutUint32(wave[4:], uint32(len(wave)-8))
	if _, _, err := DecodeAudio(t.Context(), wave, 1); err != nil {
		t.Fatal(err)
	}
}

func TestAudioDecodeWAVExtensible(t *testing.T) {
	wave := wavFixture(1, 16, 1, []byte{0, 64})
	extension := []byte{22, 0, 16, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 16, 0, 128, 0, 0, 170, 0, 56, 155, 113}
	wave = append(wave[:36], append(extension, wave[36:]...)...)
	binary.LittleEndian.PutUint32(wave[4:], uint32(len(wave)-8))
	binary.LittleEndian.PutUint32(wave[16:], 40)
	binary.LittleEndian.PutUint16(wave[20:], 0xfffe)
	audio, _, err := DecodeAudio(t.Context(), wave, 1)
	if err != nil || !slices.Equal(audio.Samples, []float32{.5}) {
		t.Fatalf("decode=%+v %v", audio, err)
	}
	wave[46] ^= 1
	if _, status, err := DecodeAudio(t.Context(), wave, 1); err == nil || status != recipecontract.AudioDecodeUnsupported {
		t.Fatalf("GUID error=%v status=%s", err, status)
	}
}

func TestAudioDecodeRejectsMalformedWAV(t *testing.T) {
	valid := wavFixture(1, 16, 1, []byte{0, 64})
	for cut := range len(valid) {
		if result, _, err := DecodeAudio(t.Context(), valid[:cut], 1); err == nil || len(result.Samples) != 0 {
			t.Fatalf("accepted prefix %d", cut)
		}
	}
	for _, test := range []struct {
		name   string
		change func([]byte) []byte
	}{
		{"zero-channels", func(b []byte) []byte { binary.LittleEndian.PutUint16(b[22:], 0); return b }},
		{"alignment", func(b []byte) []byte { binary.LittleEndian.PutUint16(b[32:], 1); return b }},
		{"byte-rate", func(b []byte) []byte { b[28] ^= 1; return b }},
		{"riff-size", func(b []byte) []byte { b[4]--; return b }},
		{"partial-frame", func(b []byte) []byte {
			b = b[:len(b)-1]
			binary.LittleEndian.PutUint32(b[4:], uint32(len(b)-8))
			binary.LittleEndian.PutUint32(b[40:], 1)
			return b
		}},
		{"duplicate-data", func(b []byte) []byte {
			b = append(b, b[36:]...)
			binary.LittleEndian.PutUint32(b[4:], uint32(len(b)-8))
			return b
		}},
		{"duplicate-fmt", func(b []byte) []byte {
			b = append(b, b[12:36]...)
			binary.LittleEndian.PutUint32(b[4:], uint32(len(b)-8))
			return b
		}},
		{"trailing-byte", func(b []byte) []byte { return append(b, 0) }},
	} {
		t.Run(test.name, func(t *testing.T) {
			if result, _, err := DecodeAudio(t.Context(), test.change(slices.Clone(valid)), 1); err == nil || len(result.Samples) != 0 {
				t.Fatal("malformed audio accepted")
			}
		})
	}
	if _, _, err := DecodeWAV(wavFixture(1, 16, 2, []byte{0, 64, 0, 64})); err == nil {
		t.Fatal("mono frontend accepted stereo")
	}
}

func TestAudioDecodeFLACIntegrity(t *testing.T) {
	encoded, err := hex.DecodeString(stereoFLACHex)
	if err != nil {
		t.Fatal(err)
	}
	audio, status, err := DecodeAudio(t.Context(), encoded, 48)
	if err != nil || status != recipecontract.AudioDecodeComplete || len(audio.Samples) != 48 || audio.Format.Channels != 2 {
		t.Fatalf("decode=%+v status=%s %v", audio, status, err)
	}
	want := []float32{0, .5, -.5, .25, .125, -.125}
	for i, v := range audio.Samples {
		if v != want[i%len(want)] {
			t.Fatalf("sample %d=%g", i, v)
		}
	}
	for cut := range len(encoded) {
		if result, _, err := DecodeAudio(t.Context(), encoded[:cut], 48); err == nil || len(result.Samples) != 0 {
			t.Fatalf("accepted FLAC prefix %d", cut)
		}
	}
	for _, test := range []struct {
		name   string
		mutate func([]byte) []byte
	}{
		{"md5", func(b []byte) []byte { b[26] ^= 1; return b }},
		{"crc", func(b []byte) []byte { b[len(b)-1] ^= 1; return b }},
		{"trailing-sync", func(b []byte) []byte { return append(b, 255) }},
		{"sample-count", func(b []byte) []byte { b[25]++; return b }},
		{"bit-depth", func(b []byte) []byte { b[20] ^= 1; return b }},
	} {
		t.Run(test.name, func(t *testing.T) {
			if result, _, err := DecodeAudio(t.Context(), test.mutate(slices.Clone(encoded)), 48); err == nil || len(result.Samples) != 0 {
				t.Fatal("corrupt FLAC accepted")
			}
		})
	}
	if _, status, err := DecodeAudio(t.Context(), encoded, 47); err == nil || status != recipecontract.AudioDecodeResourceLimit {
		t.Fatalf("budget status=%s %v", status, err)
	}
	// STREAMINFO may omit the total and checksum; frame CRC and budget still apply.
	unknown := slices.Clone(encoded)
	unknown[21] &= 0xf0
	clear(unknown[22:42])
	if _, _, err := DecodeAudio(t.Context(), unknown, 48); err != nil {
		t.Fatal(err)
	}
	if _, status, err := DecodeAudio(t.Context(), unknown, 47); err == nil || status != recipecontract.AudioDecodeResourceLimit {
		t.Fatalf("unknown-count budget=%s %v", status, err)
	}
}

func TestAudioDecodeCancellationAndUnsupported(t *testing.T) {
	ctx, cancel := context.WithCancelCause(t.Context())
	cancel(errors.New("stop"))
	if _, _, err := DecodeAudio(ctx, []byte("fLaC"), 1); !errors.Is(err, context.Canceled) {
		t.Fatal(err)
	}
	for _, data := range [][]byte{[]byte("OggS"), []byte("ID3"), []byte("RF64"), []byte("not audio")} {
		if _, status, err := DecodeAudio(t.Context(), data, 1); err == nil || status != recipecontract.AudioDecodeUnsupported {
			t.Fatalf("unsupported=%s %v", status, err)
		}
	}
	for _, bound := range []uint64{0, math.MaxUint64} {
		if _, status, err := DecodeAudio(t.Context(), wavFixture(1, 16, 1, []byte{0, 64}), bound); err == nil || status != recipecontract.AudioDecodeResourceLimit {
			t.Fatalf("invalid bound=%s %v", status, err)
		}
	}
}

func wavFixture(codec, width, channels uint16, payload []byte) []byte {
	b := append([]byte("RIFF"), make([]byte, 4)...)
	b = append(b, []byte("WAVEfmt ")...)
	b = binary.LittleEndian.AppendUint32(b, 16)
	b = binary.LittleEndian.AppendUint16(b, codec)
	b = binary.LittleEndian.AppendUint16(b, channels)
	b = binary.LittleEndian.AppendUint32(b, 16000)
	align := channels * (width / 8)
	b = binary.LittleEndian.AppendUint32(b, 16000*uint32(align))
	b = binary.LittleEndian.AppendUint16(b, align)
	b = binary.LittleEndian.AppendUint16(b, width)
	b = append(b, []byte("data")...)
	b = binary.LittleEndian.AppendUint32(b, uint32(len(payload)))
	b = append(b, payload...)
	if len(payload)%2 != 0 {
		b = append(b, 0)
	}
	binary.LittleEndian.PutUint32(b[4:], uint32(len(b)-8))
	return b
}

func FuzzAudioDecode(f *testing.F) {
	f.Add(wavFixture(1, 16, 1, []byte{0, 64}))
	flac, _ := hex.DecodeString(stereoFLACHex)
	f.Add(flac)
	f.Fuzz(func(t *testing.T, data []byte) {
		decoded, status, err := DecodeAudio(t.Context(), data, 4096)
		if err != nil && len(decoded.Samples) != 0 {
			t.Fatal("failure returned partial samples")
		}
		if err == nil && (status != recipecontract.AudioDecodeComplete || len(decoded.Samples) > 4096) {
			t.Fatal("invalid success")
		}
	})
}

// Golden hashes use libsndfile 1.2.2 to expand all 256 G.711 codewords.
func TestAudioDecodeG711Exhaustive(t *testing.T) {
	payload := make([]byte, 256)
	for i := range payload {
		payload[i] = byte(i)
	}
	for codec, want := range map[uint16]string{
		6: "d4f2bd1be9bad67461eab90762a5ddd77cb74e988c585d4a3a51a7204bdd09ec", 7: "34371823a5daca165d7cae3c7afa7ea7683ab9176cc8423deaa23c97199adc7f",
	} {
		t.Run(fmt.Sprint(codec), func(t *testing.T) {
			audio, _, err := DecodeAudio(t.Context(), wavFixture(codec, 8, 1, payload), 256)
			if err != nil {
				t.Fatal(err)
			}
			got := fmt.Sprintf("%x", sha256.Sum256(binaryschema.LittleEndian.Float32s(audio.Samples)))
			if got != want {
				t.Fatalf("decoded SHA256=%s want=%s", got, want)
			}
		})
	}
}
