package codemanifest

import (
	"slices"
	"testing"

	"overgo/internal/repoanalysis"
)

func TestBuildContextsDistinguishVariantSymbols(t *testing.T) {
	root := t.TempDir()
	linuxFile := "internal/example/run_linux.go"
	windowsFile := "internal/example/run_windows.go"
	writeGeneratorFixture(t, root, linuxFile, "package example\nfunc Run() string { return \"linux\" }\n")
	writeGeneratorFixture(t, root, windowsFile, "package example\nfunc Run() string { return \"windows\" }\n")
	snapshot, err := repoanalysis.DiscoverGo(root, "internal")
	if err != nil {
		t.Fatal(err)
	}
	selections := []repoanalysis.BuildSelection{
		variantSelection(root, "linux/amd64", linuxFile, windowsFile),
		variantSelection(root, "windows/amd64", windowsFile, linuxFile),
	}
	manifest, err := Generate(snapshot, selections, nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(manifest.BuildContexts) != 2 || len(manifest.Symbols) != 2 {
		t.Fatalf("contexts=%d symbols=%d", len(manifest.BuildContexts), len(manifest.Symbols))
	}
	contexts := []string{manifest.Symbols[0].ID.Context, manifest.Symbols[1].ID.Context}
	if !slices.Equal(contexts, []string{"linux/amd64", "windows/amd64"}) {
		t.Fatalf("symbol contexts = %v", contexts)
	}
	for _, file := range manifest.Files {
		if len(file.SelectedContexts) != 1 {
			t.Fatalf("file %s contexts = %v", file.Path, file.SelectedContexts)
		}
	}
}

func TestGeneratedAndCgoBecomeUncertainty(t *testing.T) {
	root := t.TempDir()
	generated := "internal/example/generated.go"
	cgo := "internal/example/cgo.go"
	writeGeneratorFixture(t, root, generated, "// Code generated by fixture. DO NOT EDIT.\npackage example\nfunc Generated() {}\n")
	writeGeneratorFixture(t, root, cgo, "package example\n//export CRun\nfunc CRun() {}\n")
	snapshot, err := repoanalysis.DiscoverGo(root, "internal")
	if err != nil {
		t.Fatal(err)
	}
	selection := repoanalysis.BuildSelection{
		Context: "linux/amd64", Root: root,
		Files:    map[string]bool{generated: true, cgo: true},
		Packages: map[string]string{generated: "overgo/internal/example", cgo: "overgo/internal/example"},
	}
	manifest, err := Generate(snapshot, []repoanalysis.BuildSelection{selection}, nil)
	if err != nil {
		t.Fatal(err)
	}
	kinds := map[UncertaintyKind]bool{}
	for _, boundary := range manifest.Uncertainty {
		kinds[boundary.Kind] = true
	}
	if !kinds[UncertaintyGenerated] || !kinds[UncertaintyCgo] {
		t.Fatalf("uncertainty kinds = %v", kinds)
	}
	if err := manifest.ExclusionAuthority(); err == nil {
		t.Fatal("generated and cgo boundaries authorized exclusion")
	}
}

func TestExternalInputsAffectManifestIdentity(t *testing.T) {
	root := t.TempDir()
	name := "internal/example/run.go"
	writeGeneratorFixture(t, root, name, "package example\nfunc Run() {}\n")
	snapshot, err := repoanalysis.DiscoverGo(root, "internal")
	if err != nil {
		t.Fatal(err)
	}
	selection := repoanalysis.BuildSelection{
		Context: "linux/amd64", Root: root, Files: map[string]bool{name: true},
		Packages: map[string]string{name: "overgo/internal/example"},
	}
	first, err := Generate(snapshot, []repoanalysis.BuildSelection{selection}, []ExternalInput{{
		Path: "kernels/manifest.json", ContentID: fixtureDigest, Kind: "kernel-manifest", Owner: "internal/cuda/kernel",
	}})
	if err != nil {
		t.Fatal(err)
	}
	changedDigest := "1123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	second, err := Generate(snapshot, []repoanalysis.BuildSelection{selection}, []ExternalInput{{
		Path: "kernels/manifest.json", ContentID: changedDigest, Kind: "kernel-manifest", Owner: "internal/cuda/kernel",
	}})
	if err != nil {
		t.Fatal(err)
	}
	if first.ID == second.ID {
		t.Fatal("external input content did not change manifest identity")
	}
}

func variantSelection(root, context, selected, excluded string) repoanalysis.BuildSelection {
	return repoanalysis.BuildSelection{
		Context: context, Root: root,
		Files:    map[string]bool{selected: true, excluded: false},
		Packages: map[string]string{selected: "overgo/internal/example", excluded: "overgo/internal/example"},
	}
}
