package server

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"overgo/internal/inference"
	"overgo/internal/sampling"
	"overgo/internal/tokenizer"
)

func writeInvalidRequest(response http.ResponseWriter, err error) {
	writeError(response, http.StatusBadRequest, "invalid_request_error", err.Error())
}

func writeInvalidRequestMessage(response http.ResponseWriter, message string) {
	writeError(response, http.StatusBadRequest, "invalid_request_error", message)
}

func emitGenerationError(write func(any) error, err error) error {
	return write(errorEnvelope("generation_error", err.Error()))
}

func emitNamedGenerationError(
	write func(string, any) error,
	event string,
	err error,
) error {
	return write(event, map[string]any{
		"type": event, "error": errorEnvelope("generation_error", err.Error()).Error,
	})
}

func (h *Handler) decodeProtocolJSON(
	response http.ResponseWriter,
	request *http.Request,
	target any,
	model func() string,
) bool {
	return h.decodeMultimodalJSON(response, request, target) &&
		h.requireModel(response, model())
}

type protocolGenerationPlan struct {
	evaluation inference.PromptEvaluation
	handler    *Handler
	request    *http.Request
	session    *requestSession
	prompt     preparedPrompt
	sampler    *sampling.Sampler
	maxTokens  int
	stops      []string
	// An eager final-output constraint assigns every generated byte to visible
	// content, even when the original template has a thinking suffix.
	constrainedContent bool
	tokenEventDecoder  inference.TokenEventDecoder
	// held: text a stopped turn decoded but its stop filter held back; a
	// continuation primes its filter with it.
	held string
}

type protocolGenerationResult struct {
	ids  []tokenizer.TokenID
	pump *generationPump
}

// turnEnd is how a generated turn ended, classified once for every
// protocol; each protocol only names it.
type turnEnd int

const (
	// turnEnded: the model ended the turn itself.
	turnEnded turnEnd = iota
	// turnStopped: a requested stop sequence ended it.
	turnStopped
	// turnLimited: the output token limit ended it.
	turnLimited
	// turnCalledTools: it ended in tool calls.
	turnCalledTools
)

// end classifies the turn: tool calls first, then a matched stop, then the
// output limit, so token counts alone never override a matched stop.
func (result protocolGenerationResult) end(maxTokens int, message inference.ChatMessage) turnEnd {
	switch {
	case len(message.ToolCalls) != 0:
		return turnCalledTools
	case result.pump.stopped():
		return turnStopped
	case result.pump.completion >= maxTokens:
		return turnLimited
	}
	return turnEnded
}

// chatFinish names a turn's end as chat and text completions report it.
func chatFinish(end turnEnd) string {
	switch end {
	case turnCalledTools:
		return "tool_calls"
	case turnLimited:
		return "length"
	}
	return "stop"
}

// promptTokens: the prompt's count; the provider's when the generator
// reported one (a hosted turn tokenizes at the provider), else the ids
// beyond the generated ones.
func (result protocolGenerationResult) promptTokens() int {
	if result.pump.usage != nil {
		return result.pump.usage.PromptTokens
	}
	return len(result.ids) - result.pump.generated
}

func (result protocolGenerationResult) cachedTokens() int {
	return result.pump.evaluation.Cached
}

// outputTokens: the completion's count; the provider's when reported,
// else the generated ids.
func (result protocolGenerationResult) outputTokens() int {
	if result.pump.usage != nil {
		return result.pump.usage.CompletionTokens
	}
	return result.pump.generated
}

// completionTokens: the chat completion's count; the provider's when
// reported, else the ids the completion kept past its stop.
func (result protocolGenerationResult) completionTokens() int {
	if result.pump.usage != nil {
		return result.pump.usage.CompletionTokens
	}
	return result.pump.completion
}

func (h *Handler) prepareProtocolGenerationPlan(
	response http.ResponseWriter,
	request *http.Request,
	prompt nativePrompt,
	parameters samplingParameters,
	maxTokens int,
	stops []string,
) (*protocolGenerationPlan, bool) {
	sampler, err := h.newSampler(parameters)
	if err != nil {
		writeInvalidRequest(response, err)
		return nil, false
	}
	lease, acquired := h.acquireRequestSession(request.Context(), response, -1)
	if !acquired {
		return nil, false
	}
	plan := &protocolGenerationPlan{
		handler: h, request: request, session: lease,
		sampler: sampler, maxTokens: maxTokens, stops: stops,
	}
	if err := plan.admit(prompt); err != nil {
		plan.release()
		writePromptRefusal(response, err)
		return nil, false
	}
	return plan, true
}

// turn: one more prompt on the plan's session and sampling. A multi-prompt
// completion admits every prompt before any generates.
func (plan *protocolGenerationPlan) turn(prompt nativePrompt) (*protocolGenerationPlan, error) {
	next := &protocolGenerationPlan{
		handler: plan.handler, request: plan.request, session: plan.session,
		sampler: plan.sampler, maxTokens: plan.maxTokens, stops: plan.stops,
	}
	return next, next.admit(prompt)
}

// admit prepares the prompt and holds it to the model context. Prepared IDs
// include projected media and any reusable prefix; decode shifting cannot
// make an oversized initial prompt fit. An unknown context or an
// untokenized provider prompt stays with its generator.
func (plan *protocolGenerationPlan) admit(prompt nativePrompt) error {
	prepared, err := plan.handler.preparePrompt(plan.request.Context(), prompt, true)
	if err != nil {
		return err
	}
	if properties, ok := plan.handler.generator.(ModelPropertiesAPI); ok {
		limit := uint64(properties.ModelProperties().ContextLength)
		if limit > 0 && uint64(len(prepared.TokenIDs)) > limit {
			return contextLengthError{tokens: len(prepared.TokenIDs), limit: limit}
		}
	}
	plan.prompt = prepared
	return nil
}

type contextLengthError struct {
	tokens int
	limit  uint64
}

// Error names the prompt's size against the model context.
func (failure contextLengthError) Error() string {
	return fmt.Sprintf(
		"prompt has %d tokens, exceeding the model context length of %d tokens",
		failure.tokens, failure.limit,
	)
}

// writePromptRefusal: an oversized prompt is the client's error; any other
// preparation failure is the generation's.
func writePromptRefusal(response http.ResponseWriter, err error) {
	if _, exceeded := errors.AsType[contextLengthError](err); exceeded {
		failure := errorEnvelope("invalid_request_error", err.Error())
		failure.Error.Code = "context_length_exceeded"
		writeJSON(response, http.StatusBadRequest, failure)
		return
	}
	writeGenerationError(response, err)
}

func (plan *protocolGenerationPlan) release() {
	plan.handler.releaseSession(plan.session)
}

func (plan *protocolGenerationPlan) context() context.Context {
	return plan.request.Context()
}

func (plan *protocolGenerationPlan) run(
	emit func(string) error,
) (protocolGenerationResult, error) {
	return plan.runWithSampler(plan.sampler, emit)
}

func (plan *protocolGenerationPlan) runChoice(
	index int,
	emit func(string) error,
) (protocolGenerationResult, error) {
	sampler, err := samplerForChoice(plan.sampler, index)
	if err != nil {
		return protocolGenerationResult{}, err
	}
	return plan.runWithSampler(sampler, emit)
}

func (plan *protocolGenerationPlan) runWithSampler(
	sampler *sampling.Sampler,
	emit func(string) error,
) (protocolGenerationResult, error) {
	options := plan.handler.protocolGenerationOptions(
		plan.maxTokens, sampler, plan.prompt.TokenIDs, plan.prompt.ProjectedInputs,
	)
	options.TokenEventDecoder = plan.tokenEventDecoder
	// The selected session may use a scheduler instead of the inspected model.
	// Never infer scheduler support from the underlying Runner.
	if provider, ok := plan.session.Model().(promptCacheProvider); ok {
		options.CachePrompt = provider.SupportsPromptCache()
	}
	options.OnPromptEvaluated = func(evaluation inference.PromptEvaluation) {
		plan.evaluation = evaluation
	}
	pump := newGenerationPump(plan.stops, emit)
	pump.filter.prime(plan.held)
	ids, err := plan.handler.pumpGeneration(plan.context(), plan.session, plan.prompt.Text, options, pump)
	return protocolGenerationResult{ids: ids, pump: pump}, err
}

// countTurn is every protocol's input-token count: the protocol's turn
// builder, the one its generation route calls, gives the chat request and
// prompt tools, and the count measures the prompt they format (pending tool
// calls are not executed). A refusal the builder wrote answers false.
func (h *Handler) countTurn(response http.ResponseWriter, request *http.Request, object bool, turn func() (chatCompletionRequest, []inference.ChatTool, bool)) {
	formatter, ok := h.requireProtocolTokenCounting(response, request)
	if !ok {
		return
	}
	chat, tools, ok := turn()
	if !ok {
		return
	}
	normalized, err := h.normalizeChatPrompt(request.Context(), formatter, chat, tools, false)
	if err != nil {
		writeInvalidRequest(response, err)
		return
	}
	h.writeProtocolInputTokenCount(response, request, normalized, object)
}

func (h *Handler) writeProtocolInputTokenCount(
	response http.ResponseWriter,
	request *http.Request,
	prompt nativePrompt,
	object bool,
) {
	prepared, err := h.preparePrompt(request.Context(), prompt, true)
	if err != nil {
		if nativePromptHasMedia(prompt) {
			writeGenerationError(response, err)
		} else {
			writeInvalidRequest(response, err)
		}
		return
	}
	payload := map[string]any{"input_tokens": len(prepared.TokenIDs)}
	if object {
		payload["object"] = "response.input_tokens"
	}
	writeJSON(response, http.StatusOK, payload)
}

type toolDeltaStream struct {
	output        inference.ChatOutputStream
	buffered      strings.Builder
	names         []string
	arguments     []strings.Builder
	started       bool
	promptAware   bool
	sentContent   strings.Builder
	sentReasoning strings.Builder
}

type toolDeltaSink struct {
	Reasoning func(string) error
	Content   func(string) error
	Tool      func(inference.ChatToolCallDelta) error
}

func (h *Handler) requireChatFormatter(
	response http.ResponseWriter,
) (ChatFormatter, bool) {
	formatter, ok := h.generator.(ChatFormatter)
	if !ok {
		writeError(
			response,
			http.StatusNotImplemented,
			errorCodeUnsupportedOperation,
			"chat formatting is unavailable",
		)
	}
	return formatter, ok
}

func (h *Handler) requireProtocolTokenCounting(
	response http.ResponseWriter,
	request *http.Request,
) (ChatFormatter, bool) {
	formatter, ok := h.requireChatFormatter(response)
	if !ok || !h.requireTokenCounting(response) {
		return nil, false
	}
	return formatter, true
}

func (h *Handler) requireChatOutputParser(
	response http.ResponseWriter,
	feature string,
) (ChatOutputParser, bool) {
	parser, ok := h.generator.(ChatOutputParser)
	if !ok {
		writeError(
			response, http.StatusNotImplemented, errorCodeUnsupportedOperation,
			feature+" output parsing is unavailable",
		)
	}
	return parser, ok
}

func (h *Handler) requireTokenCounting(response http.ResponseWriter) bool {
	if _, ok := h.generator.(TokenizationAPI); ok {
		return true
	}
	writeError(
		response,
		http.StatusNotImplemented,
		errorCodeUnsupportedOperation,
		"token counting is unavailable",
	)
	return false
}

func newPromptChatDeltaStream(plan *protocolGenerationPlan, tools []inference.ChatTool) (*toolDeltaStream, error) {
	plan.tokenEventDecoder = nil
	if plan.constrainedContent {
		return nil, nil
	}
	provider, ok := plan.handler.generator.(PromptChatOutputStreamProvider)
	if !ok {
		return nil, nil
	}
	output, err := provider.NewChatOutputStreamForPrompt(plan.prompt.Text, plan.prompt.TokenIDs, tools)
	if err != nil {
		return nil, err
	}
	if output == nil {
		return nil, errors.New("chat output stream provider returned no stream")
	}
	if decoder, ok := output.(inference.ChatOutputTokenDecoder); ok {
		plan.tokenEventDecoder = decoder.TokenEventDecoder()
	}
	return &toolDeltaStream{output: output, promptAware: true}, nil
}

func newToolDeltaStream(
	generator Generator,
	tools []inference.ChatTool,
) (*toolDeltaStream, error) {
	result := &toolDeltaStream{}
	if len(tools) == 0 {
		return result, nil
	}
	provider, ok := generator.(ChatOutputStreamProvider)
	if !ok {
		return result, nil
	}
	output, err := provider.NewChatOutputStream(tools)
	if err != nil {
		return nil, err
	}
	result.output = output
	return result, nil
}

func (s *toolDeltaStream) accept(piece string) ([]inference.ChatToolCallDelta, error) {
	if !s.promptAware {
		s.buffered.WriteString(piece)
	}
	if s.output == nil || piece == "" {
		return nil, nil
	}
	deltas, err := s.output.Accept(piece)
	if err != nil {
		return nil, err
	}
	for _, delta := range deltas {
		if !chatDeltaHasTool(delta) {
			continue
		}
		if delta.Index < 0 {
			return nil, fmt.Errorf("tool stream returned negative index %d", delta.Index)
		}
		for len(s.names) <= delta.Index {
			s.names = append(s.names, "")
			s.arguments = append(s.arguments, strings.Builder{})
		}
		if delta.Started {
			s.names[delta.Index] = delta.Name
			s.started = true
		}
		if delta.Arguments != "" {
			s.arguments[delta.Index].WriteString(delta.Arguments)
		}
	}
	return deltas, nil
}

func (s *toolDeltaStream) route(piece string, sink toolDeltaSink) error {
	deltas, err := s.accept(piece)
	if err != nil {
		return err
	}
	for _, delta := range deltas {
		if delta.ReasoningContent != "" && sink.Reasoning != nil {
			if err := sink.Reasoning(delta.ReasoningContent); err != nil {
				return err
			}
			if s.promptAware {
				s.sentReasoning.WriteString(delta.ReasoningContent)
			}
		}
		if delta.Content != "" && sink.Content != nil {
			if err := sink.Content(delta.Content); err != nil {
				return err
			}
			if s.promptAware {
				s.sentContent.WriteString(delta.Content)
			}
		}
		if sink.Tool != nil && chatDeltaHasTool(delta) {
			if err := sink.Tool(delta); err != nil {
				return err
			}
		}
	}
	return nil
}

func (s *toolDeltaStream) parse(parser ChatOutputParser, tools []inference.ChatTool) (inference.ChatMessage, error) {
	if s.promptAware {
		return s.output.Finish()
	}
	return parser.ParseChatOutput(s.text(), tools)
}

func chatDeltaHasTool(delta inference.ChatToolCallDelta) bool {
	return delta.Started || delta.Name != "" || delta.Arguments != ""
}

func (s *toolDeltaStream) remaining(message inference.ChatMessage) (inference.ChatMessage, error) {
	if !s.promptAware {
		if s.started {
			message.Content, message.ReasoningContent = "", ""
		}
		return message, nil
	}
	var ok bool
	message.Content, ok = strings.CutPrefix(message.Content, s.sentContent.String())
	if !ok {
		return inference.ChatMessage{}, errors.New("chat visible output changed after streaming")
	}
	message.ReasoningContent, ok = strings.CutPrefix(message.ReasoningContent, s.sentReasoning.String())
	if !ok {
		return inference.ChatMessage{}, errors.New("chat reasoning output changed after streaming")
	}
	return message, nil
}

func (s *toolDeltaStream) text() string {
	return s.buffered.String()
}

func (s *toolDeltaStream) streamed(index int) bool {
	return index >= 0 && index < len(s.names) && s.names[index] != ""
}

func (s *toolDeltaStream) argumentText(index int) string {
	if index < 0 || index >= len(s.arguments) {
		return ""
	}
	return s.arguments[index].String()
}

func boundedProtocolTokens(
	configured *int,
	fallback, limit int,
	field string,
	required bool,
) (int, error) {
	value := fallback
	if configured == nil {
		if required {
			return 0, fmt.Errorf("%s is required", field)
		}
	} else {
		value = *configured
	}
	if value < 0 || value > limit {
		return 0, fmt.Errorf("%s must be in [0,%d]", field, limit)
	}
	return value, nil
}

func (h *Handler) protocolGenerationOptions(
	maxTokens int,
	sampler *sampling.Sampler,
	promptIDs []tokenizer.TokenID,
	projected *inference.ProjectedInputs,
) inference.GenerateOptions {
	return inference.GenerateOptions{
		MaxNewTokens:    maxTokens,
		Sampler:         sampler,
		ParseSpecial:    true,
		ContextShift:    h.config.ContextShift,
		PromptTokenIDs:  promptIDs,
		CachePrompt:     projected != nil,
		ProjectedInputs: projected,
	}
}

func (h *Handler) configureChatToolGrammar(
	response http.ResponseWriter,
	parameters *samplingParameters,
	tools []inference.ChatTool,
	required, thinking, parallel bool,
) bool {
	if len(tools) == 0 {
		return true
	}
	provider, ok := h.generator.(ChatToolGrammarProvider)
	if !ok {
		writeError(
			response,
			http.StatusNotImplemented,
			errorCodeUnsupportedOperation,
			"tool-call grammar generation is unavailable",
		)
		return false
	}
	source, root, patterns, err := provider.ChatToolGrammar(
		tools, required, thinking, parallel,
	)
	if err != nil {
		writeInvalidRequest(response, err)
		return false
	}
	parameters.Grammar = source
	parameters.GrammarRoot = root
	parameters.GrammarLazy = len(patterns) != 0
	parameters.GrammarTriggerPatterns = patterns
	return true
}

// writeRefusableResult reports one route-family outcome: a refusal
// error maps to unprocessable-entity with the family refusal code,
// success writes the value at the given status.
func writeRefusableResult(response http.ResponseWriter, status int, value any, err error, refusal string) {
	if err != nil {
		writeError(response, http.StatusUnprocessableEntity, refusal, err.Error())
		return
	}
	writeJSON(response, status, value)
}
