package parity

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"testing"
)

// fixtureBytes refuses absent or changed oracle artifacts. A missing external
// model remains a separate validation boundary; it cannot become a test pass
// by skipping the declared fixture itself.
func fixtureBytes(path, wantSHA string) ([]byte, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	actual := sha256.Sum256(data)
	if hex.EncodeToString(actual[:]) != wantSHA {
		return nil, fmt.Errorf("fixture %s has unexpected sha256 %x", path, actual)
	}
	return data, nil
}

func TestParityFixtureAdmission(t *testing.T) {
	// The real-model token output was generated by Colibri's HF Transformers
	// make_olmoe_real_oracle.py at f028d26b422144ed4a69ad9aeaee2553ce0f9572.
	// Its script SHA256 is b6be54f74aa55c2767bf46c37efbb9fda96a915589e4d2269b60030553.
	// This pins an independent reference, not Overgo real-model parity.
	realPath := filepath.Join("testdata", "olmoe_real_reference.json")
	real, err := fixtureBytes(realPath, "8f8f3140615b0033dd3d31624bab979b0737b91cda0300a64756bd039a459037")
	if err != nil {
		t.Fatal(err)
	}
	var reference struct {
		PromptIDs []int `json:"prompt_ids"`
		FullIDs   []int `json:"full_ids"`
	}
	if err := json.Unmarshal(real, &reference); err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(reference.PromptIDs, []int{510, 5347, 273, 6181, 310}) ||
		len(reference.FullIDs) != len(reference.PromptIDs)+12 ||
		!slices.Equal(reference.FullIDs[:len(reference.PromptIDs)], reference.PromptIDs) ||
		!slices.Equal(reference.FullIDs[len(reference.PromptIDs):], []int{7785, 15, 187, 187, 510, 3565, 3448, 273, 6181, 310, 5112, 15}) {
		t.Fatalf("independent OLMoE continuation differs: %+v", reference)
	}

	// The tiny structural artifact is produced by a separate Python GGUF v3
	// serializer and has its own inventory and byte-level oracle below.
	tinyPath := filepath.Join("testdata", "olmoe_tiny.gguf")
	if _, err := fixtureBytes(tinyPath, "191e65fe8477cd1e50a9d14ee832aa6bf10b39980b61189831f2f44f2a05a5d1"); err != nil {
		t.Fatal(err)
	}
	if _, err := os.ReadFile(filepath.Join("testdata", "olmoe_tiny.json")); err != nil {
		t.Fatal(err)
	}
	if _, err := fixtureBytes(filepath.Join(t.TempDir(), "absent.gguf"), "191e65fe8477cd1e50a9d14ee832aa6bf10b39980b61189831f2f44f2a05a5d1"); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("missing fixture admitted: %v", err)
	}
	changed := filepath.Join(t.TempDir(), "changed.gguf")
	if err := os.WriteFile(changed, []byte("wrong"), 0600); err != nil {
		t.Fatal(err)
	}
	if _, err := fixtureBytes(changed, "191e65fe8477cd1e50a9d14ee832aa6bf10b39980b61189831f2f44f2a05a5d1"); err == nil {
		t.Fatal("changed fixture admitted")
	}
}
