package main

import (
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

type tableSpec struct {
	cType  string
	cName  string
	goType string
	goName string
	size   int
}

var tableSpecs = []tableSpec{
	{"uint64_t", "iq2xxs_grid", "uint64", "iq2XXSGrid", 256},
	{"uint64_t", "iq2xs_grid", "uint64", "iq2XSGrid", 512},
	{"uint64_t", "iq2s_grid", "uint64", "iq2SGrid", 1024},
	{"uint32_t", "iq3xxs_grid", "uint32", "iq3XXSGrid", 256},
	{"uint32_t", "iq3s_grid", "uint32", "iq3SGrid", 512},
	{"uint64_t", "iq1s_grid", "uint64", "iq1SGrid", 2048},
}

func main() {
	var sourcePath string
	var outputPath string
	var cudaOutputPath string
	var upstreamCommit string
	flag.StringVar(&sourcePath, "source", "", "path to the pinned upstream ggml-common.h")
	flag.StringVar(&outputPath, "out", "", "generated Go output path")
	flag.StringVar(&cudaOutputPath, "cuda-out", "", "optional generated CUDA header path")
	flag.StringVar(&upstreamCommit, "commit", "", "audited upstream commit")
	flag.Parse()

	if sourcePath == "" || outputPath == "" || upstreamCommit == "" {
		fmt.Fprintln(os.Stderr, "-source, -out, and -commit are required")
		os.Exit(2)
	}
	source, err := os.ReadFile(sourcePath)
	if err != nil {
		fatal(err)
	}
	sourceHash := sha256.Sum256(source)

	extracted := make(map[string][]string, len(tableSpecs))
	for _, spec := range tableSpecs {
		values, err := extractTable(string(source), spec)
		if err != nil {
			fatal(err)
		}
		extracted[spec.cName] = values
	}

	var generated strings.Builder
	fmt.Fprintln(&generated, "// Code generated by cmd/gen-iq-tables; DO NOT EDIT.")
	fmt.Fprintf(
		&generated,
		"// Source: llama.cpp %s, ggml/src/ggml-common.h SHA-256 %x.\n\n",
		upstreamCommit,
		sourceHash,
	)
	fmt.Fprintln(&generated, "package quant")
	for _, spec := range tableSpecs {
		values := extracted[spec.cName]
		fmt.Fprintf(
			&generated,
			"\nvar %s = [...]%s{\n",
			spec.goName,
			spec.goType,
		)
		for index, value := range values {
			if index%4 == 0 {
				fmt.Fprint(&generated, "\t")
			}
			fmt.Fprintf(&generated, "%s,", value)
			if index%4 == 3 || index == len(values)-1 {
				fmt.Fprintln(&generated)
			} else {
				fmt.Fprint(&generated, " ")
			}
		}
		fmt.Fprintln(&generated, "}")
	}

	formatted, err := format.Source([]byte(generated.String()))
	if err != nil {
		fatal(fmt.Errorf("format generated source: %w", err))
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		fatal(err)
	}
	if cudaOutputPath != "" {
		if err := writeCUDAHeader(
			cudaOutputPath,
			upstreamCommit,
			sourceHash,
			extracted,
		); err != nil {
			fatal(err)
		}
	}
}

func writeCUDAHeader(
	outputPath string,
	upstreamCommit string,
	sourceHash [sha256.Size]byte,
	extracted map[string][]string,
) error {
	var generated strings.Builder
	fmt.Fprintln(&generated, "// Code generated by cmd/gen-iq-tables; DO NOT EDIT.")
	fmt.Fprintf(
		&generated,
		"// Source: llama.cpp %s, ggml/src/ggml-common.h SHA-256 %x.\n",
		upstreamCommit,
		sourceHash,
	)
	fmt.Fprintln(&generated, "#pragma once")
	for _, spec := range tableSpecs {
		values := extracted[spec.cName]
		cudaType := "unsigned long long"
		suffix := "ULL"
		if spec.goType == "uint32" {
			cudaType = "unsigned int"
			suffix = "U"
		}
		fmt.Fprintf(
			&generated,
			"\n__device__ __constant__ %s %s[%d] = {\n",
			cudaType,
			spec.goName,
			spec.size,
		)
		for index, value := range values {
			if index%4 == 0 {
				fmt.Fprint(&generated, "    ")
			}
			fmt.Fprintf(&generated, "%s%s,", value, suffix)
			if index%4 == 3 || index == len(values)-1 {
				fmt.Fprintln(&generated)
			} else {
				fmt.Fprint(&generated, " ")
			}
		}
		fmt.Fprintln(&generated, "};")
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, []byte(generated.String()), 0o644)
}

func extractTable(source string, spec tableSpec) ([]string, error) {
	pattern := regexp.MustCompile(
		`(?s)GGML_TABLE_BEGIN\(\s*` + regexp.QuoteMeta(spec.cType) +
			`,\s*` + regexp.QuoteMeta(spec.cName) +
			`,\s*[^\)]+\)(.*?)GGML_TABLE_END\(\)`,
	)
	match := pattern.FindStringSubmatch(source)
	if match == nil {
		return nil, fmt.Errorf("table %s was not found", spec.cName)
	}
	valuePattern := regexp.MustCompile(`0[xX][0-9a-fA-F]+|\b[0-9]+\b`)
	rawValues := valuePattern.FindAllString(match[1], -1)
	if len(rawValues) != spec.size {
		return nil, fmt.Errorf(
			"table %s has %d values, need %d",
			spec.cName,
			len(rawValues),
			spec.size,
		)
	}
	values := make([]string, len(rawValues))
	for index, raw := range rawValues {
		value, err := strconv.ParseUint(raw, 0, 64)
		if err != nil {
			return nil, fmt.Errorf("%s value %q: %w", spec.cName, raw, err)
		}
		if spec.goType == "uint32" && value > uint64(^uint32(0)) {
			return nil, fmt.Errorf("%s value %q exceeds uint32", spec.cName, raw)
		}
		width := 16
		if spec.goType == "uint32" {
			width = 8
		}
		values[index] = fmt.Sprintf("0x%0*x", width, value)
	}
	return values, nil
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
