// Code generated by cmd/kernel-bindings; DO NOT EDIT.

package kernel

const (
	BundleABIVersion     = 44
	BundleTarget         = "compute_89"
	BundleDefaultThreads = 256
	BundleVAEConvTile    = 64
	VectorAddSHA256      = "f0c6eedbbae221be3342bbbb8f782e5413c84515f362cca533905f7f9510c974"
	TorchCUDARandnSHA256 = "e0a682f3821e61e9be8aa13192986c38010b60d588c027887a07e2681118df59"
	OpsF32SHA256         = "9fc8f10998013358f690d3e55fe5e97aefbfcc17f58a8747cb902d0570783214"
)

var bundleAssets = [...]bundleAsset{
	{name: "vector_add.ptx", data: VectorAddPTX, sha256: VectorAddSHA256},
	{name: "torch_cuda_randn.ptx", data: TorchCUDARandnPTX, sha256: TorchCUDARandnSHA256},
	{name: "ops_f32.ptx", data: OpsF32PTX, sha256: OpsF32SHA256},
}
