// Code generated by cmd/kernel-bindings; DO NOT EDIT.

package kernel

const (
	BundleABIVersion = 36
	BundleTarget     = "compute_89"
	VectorAddSHA256  = "af74febeae5bb087f35610f7d194695c10374bc7aed4a224da6072a56e59d159"
	OpsF32SHA256     = "6a7137a49c37c4088599ced94f88521878ecd711081caa0387bfa9a842f8e269"
)

var bundleAssets = [...]bundleAsset{
	{name: "vector_add.ptx", data: VectorAddPTX, sha256: VectorAddSHA256},
	{name: "ops_f32.ptx", data: OpsF32PTX, sha256: OpsF32SHA256},
}
