// Code generated by cmd/kernel-bindings; DO NOT EDIT.

package kernel

const (
	BundleABIVersion = 36
	BundleTarget     = "compute_89"
	VectorAddSHA256  = "af74febeae5bb087f35610f7d194695c10374bc7aed4a224da6072a56e59d159"
	OpsF32SHA256     = "c4bfc2e51b8966a3c65cfd339a46e60e470e29cf2fb2b9019d66e323ab01ca82"
)

var bundleAssets = [...]bundleAsset{
	{name: "vector_add.ptx", data: VectorAddPTX, sha256: VectorAddSHA256},
	{name: "ops_f32.ptx", data: OpsF32PTX, sha256: OpsF32SHA256},
}
