package main

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"overgo/internal/gguf"
	"overgo/internal/testskip"
)

func TestExecuteHashesAndChecksManifest(t *testing.T) {
	path := writeHashFixture(t)
	params := parameters{
		input:  path,
		xxh64:  true,
		sha1:   true,
		sha256: true,
		uuid:   true,
	}
	var generated bytes.Buffer
	code, err := execute(params, &generated)
	if err != nil || code != exitSuccess {
		t.Fatalf("generate code/error = %d/%v", code, err)
	}
	if !strings.Contains(generated.String(), path+":weight") ||
		!strings.Contains(generated.String(), "uuid") {
		t.Fatalf("output =\n%s", generated.String())
	}

	manifestPath := filepath.Join(t.TempDir(), "hashes.txt")
	if err := os.WriteFile(manifestPath, generated.Bytes(), 0o600); err != nil {
		t.Fatal(err)
	}
	params.manifest = manifestPath
	params.xxh64 = false
	params.sha1 = false
	params.sha256 = false
	params.uuid = false
	var checked bytes.Buffer
	code, err = execute(params, &checked)
	if err != nil || code != exitSuccess ||
		!strings.Contains(checked.String(), " -  Ok") {
		t.Fatalf("check code/error/output = %d/%v\n%s", code, err, checked.String())
	}

	corrupt := strings.Replace(generated.String(), "sha256    ", "sha256    00", 1)
	if err := os.WriteFile(manifestPath, []byte(corrupt), 0o600); err != nil {
		t.Fatal(err)
	}
	params.sha256 = true
	code, err = execute(params, &bytes.Buffer{})
	if err != nil || code != exitFailure {
		t.Fatalf("mismatch code/error = %d/%v", code, err)
	}
}

func TestExecuteMatchesPinnedLlamaCPPGGUFHash(t *testing.T) {
	if testing.Short() {
		t.Skip(testskip.ShortIntegration + ": requires pinned llama-gguf-hash")
	}
	oracle := os.Getenv("OVERGO_GGUF_HASH_ORACLE")
	if oracle == "" {
		t.Skip("set OVERGO_GGUF_HASH_ORACLE to pinned llama-gguf-hash")
	}
	path := writeHashFixture(t)
	var got bytes.Buffer
	code, err := execute(parameters{
		input:  path,
		xxh64:  true,
		sha1:   true,
		sha256: true,
		uuid:   true,
	}, &got)
	if err != nil || code != exitSuccess {
		t.Fatalf("Go code/error = %d/%v", code, err)
	}
	command := exec.Command(oracle, "--all", "--uuid", path)
	command.Dir = filepath.Dir(oracle)
	want, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("pinned oracle: %v\n%s", err, want)
	}
	normalizedWant := strings.ReplaceAll(string(want), "\r\n", "\n")
	if got.String() != normalizedWant {
		t.Fatalf("Go output:\n%s\npinned output:\n%s", got.String(), want)
	}
}

func writeHashFixture(t *testing.T) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "hash.gguf")
	destination, err := os.Create(path)
	if err != nil {
		t.Fatal(err)
	}
	payload := make([]byte, 18)
	for index := range payload {
		payload[index] = byte(index*19 + 5)
	}
	err = gguf.Write(
		destination,
		nil,
		[]gguf.TensorData{{
			Name:  "weight",
			Shape: []uint64{32},
			Type:  gguf.DTypeQ4_0,
			Data:  bytes.NewReader(payload),
		}},
		gguf.WriteOptions{},
	)
	if closeErr := destination.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		t.Fatal(err)
	}
	return path
}
