package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

type kernelManifest struct {
	ABIVersion int            `json:"abiVersion"`
	Target     string         `json:"target"`
	Modules    []kernelModule `json:"modules"`
}

type kernelModule struct {
	Asset           string                 `json:"asset"`
	AssetSHA256     string                 `json:"assetSha256"`
	Functions       []string               `json:"functions"`
	ArgumentLayouts []kernelArgumentLayout `json:"argumentLayouts"`
}

type kernelArgumentLayout struct {
	Parameters []string `json:"parameters"`
	Functions  []string `json:"functions"`
}

func main() {
	manifestPath := flag.String("manifest", "kernels/manifest.json", "kernel manifest")
	outputPath := flag.String(
		"output",
		"internal/cuda/executor/kernel_bindings_generated.go",
		"generated Go file",
	)
	kernelOutputPath := flag.String(
		"kernel-output",
		"internal/cuda/kernel/manifest_generated.go",
		"generated kernel manifest Go file",
	)
	check := flag.Bool("check", false, "reject stale output")
	flag.Parse()
	if err := run(*manifestPath, *outputPath, *kernelOutputPath, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(manifestPath, outputPath, kernelOutputPath string, check bool) error {
	document, err := os.ReadFile(manifestPath)
	if err != nil {
		return err
	}
	generated, err := generateBindings(document)
	if err != nil {
		return err
	}
	kernelGenerated, err := generateKernelManifest(document)
	if err != nil {
		return err
	}
	if check {
		current, readErr := os.ReadFile(outputPath)
		if readErr != nil {
			return readErr
		}
		if !bytes.Equal(current, generated) {
			return errors.New("CUDA kernel bindings are stale")
		}
		kernelCurrent, readErr := os.ReadFile(kernelOutputPath)
		if readErr != nil {
			return readErr
		}
		if !bytes.Equal(kernelCurrent, kernelGenerated) {
			return errors.New("CUDA kernel manifest constants are stale")
		}
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(outputPath, generated, 0o644); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(kernelOutputPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(kernelOutputPath, kernelGenerated, 0o644)
}

func generateKernelManifest(document []byte) ([]byte, error) {
	var manifest kernelManifest
	if err := json.Unmarshal(document, &manifest); err != nil {
		return nil, err
	}
	if manifest.ABIVersion < 1 || manifest.Target == "" || len(manifest.Modules) == 0 {
		return nil, errors.New("CUDA kernel ABI identity is incomplete")
	}
	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by cmd/kernel-bindings; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package kernel")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "const (")
	fmt.Fprintf(&output, "\tBundleABIVersion = %d\n", manifest.ABIVersion)
	fmt.Fprintf(&output, "\tBundleTarget = %q\n", manifest.Target)
	for _, module := range manifest.Modules {
		if module.Asset == "" || module.AssetSHA256 == "" {
			return nil, errors.New("CUDA kernel asset identity is incomplete")
		}
		fmt.Fprintf(
			&output,
			"\t%sSHA256 = %q\n",
			assetIdentifier(module.Asset),
			module.AssetSHA256,
		)
	}
	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "var bundleAssets = [...]bundleAsset{")
	for _, module := range manifest.Modules {
		identifier := assetIdentifier(module.Asset)
		fmt.Fprintf(
			&output,
			"\t{name: %q, data: %sPTX, sha256: %sSHA256},\n",
			filepath.Base(module.Asset), identifier, identifier,
		)
	}
	fmt.Fprintln(&output, "}")
	return format.Source(output.Bytes())
}

func generateBindings(document []byte) ([]byte, error) {
	var manifest kernelManifest
	decoder := json.NewDecoder(bytes.NewReader(document))
	if err := decoder.Decode(&manifest); err != nil {
		return nil, err
	}
	if len(manifest.Modules) == 0 {
		return nil, errors.New("CUDA kernel manifest contains no modules")
	}
	var functions []string
	argumentCounts := make(map[string]int)
	seenNames := make(map[string]struct{})
	seenIDs := make(map[string]string)
	for _, module := range manifest.Modules {
		if !strings.HasSuffix(filepath.ToSlash(module.Asset), "/ops_f32.ptx") {
			continue
		}
		for _, name := range module.Functions {
			if name == "" {
				return nil, errors.New("CUDA kernel manifest contains an empty function")
			}
			if _, duplicate := seenNames[name]; duplicate {
				return nil, fmt.Errorf("CUDA kernel manifest repeats function %q", name)
			}
			identifier := kernelIdentifier(name)
			if previous, collision := seenIDs[identifier]; collision {
				return nil, fmt.Errorf(
					"CUDA kernel functions %q and %q share identifier %q",
					previous, name, identifier,
				)
			}
			seenNames[name] = struct{}{}
			seenIDs[identifier] = name
			functions = append(functions, name)
		}
		for _, layout := range module.ArgumentLayouts {
			for _, name := range layout.Functions {
				if _, duplicate := argumentCounts[name]; duplicate {
					return nil, fmt.Errorf("CUDA kernel manifest repeats argument layout for %q", name)
				}
				argumentCounts[name] = len(layout.Parameters)
			}
		}
	}
	if len(functions) == 0 {
		return nil, errors.New("CUDA operation module contains no functions")
	}
	for _, name := range functions {
		if _, ok := argumentCounts[name]; !ok {
			return nil, fmt.Errorf("CUDA kernel manifest omits argument layout for %q", name)
		}
	}

	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by cmd/kernel-bindings; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package executor")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, `import "overgo/internal/cuda/driver"`)
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "type kernelFunctionID uint16")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "const (")
	for index, name := range functions {
		assignment := ""
		if index == 0 {
			assignment = " kernelFunctionID = iota"
		}
		fmt.Fprintf(&output, "\t%s%s\n", kernelIdentifier(name), assignment)
	}
	fmt.Fprintln(&output, "\tkernelFunctionCount")
	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "var kernelFunctionNames = [...]string{")
	for _, name := range functions {
		fmt.Fprintf(&output, "\t%q,\n", name)
	}
	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "var kernelFunctionArgumentCounts = [...]uint16{")
	for _, name := range functions {
		fmt.Fprintf(&output, "\t%d,\n", argumentCounts[name])
	}
	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "type boundKernel struct {")
	fmt.Fprintln(&output, "\tfunction driver.Function")
	fmt.Fprintln(&output, "\tid kernelFunctionID")
	fmt.Fprintln(&output, "\targumentCount uint16")
	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "type functionSet [kernelFunctionCount]boundKernel")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "func loadFunctions(lib *driver.Library, module driver.Module) (functionSet, error) {")
	fmt.Fprintln(&output, "\tvar result functionSet")
	fmt.Fprintln(&output, "\tfor id, name := range kernelFunctionNames {")
	fmt.Fprintln(&output, "\t\tfunction, err := lib.ModuleFunction(module, name)")
	fmt.Fprintln(&output, "\t\tif err != nil {")
	fmt.Fprintln(&output, "\t\t\treturn functionSet{}, err")
	fmt.Fprintln(&output, "\t\t}")
	fmt.Fprintln(&output, "\t\tresult[id] = boundKernel{")
	fmt.Fprintln(&output, "\t\t\tfunction: function,")
	fmt.Fprintln(&output, "\t\t\tid: kernelFunctionID(id),")
	fmt.Fprintln(&output, "\t\t\targumentCount: kernelFunctionArgumentCounts[id],")
	fmt.Fprintln(&output, "\t\t}")
	fmt.Fprintln(&output, "\t}")
	fmt.Fprintln(&output, "\treturn result, nil")
	fmt.Fprintln(&output, "}")
	return format.Source(output.Bytes())
}

func kernelIdentifier(name string) string {
	var result strings.Builder
	result.WriteString("kernel")
	for _, part := range strings.Split(name, "_") {
		if part == "" {
			continue
		}
		result.WriteString(strings.ToUpper(part[:1]))
		result.WriteString(part[1:])
	}
	return result.String()
}

func assetIdentifier(path string) string {
	name := strings.TrimSuffix(filepath.Base(path), filepath.Ext(path))
	identifier := strings.TrimPrefix(kernelIdentifier(name), "kernel")
	return strings.ReplaceAll(identifier, "Cuda", "CUDA")
}
