package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

type kernelManifest struct {
	Modules []kernelModule `json:"modules"`
}

type kernelModule struct {
	Asset     string   `json:"asset"`
	Functions []string `json:"functions"`
}

func main() {
	manifestPath := flag.String("manifest", "kernels/manifest.json", "kernel manifest")
	outputPath := flag.String(
		"output",
		"internal/cuda/executor/kernel_bindings_generated.go",
		"generated Go file",
	)
	check := flag.Bool("check", false, "reject stale output")
	flag.Parse()
	if err := run(*manifestPath, *outputPath, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(manifestPath, outputPath string, check bool) error {
	document, err := os.ReadFile(manifestPath)
	if err != nil {
		return err
	}
	generated, err := generateBindings(document)
	if err != nil {
		return err
	}
	if check {
		current, readErr := os.ReadFile(outputPath)
		if readErr != nil {
			return readErr
		}
		if !bytes.Equal(current, generated) {
			return errors.New("CUDA kernel bindings are stale")
		}
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, generated, 0o644)
}

func generateBindings(document []byte) ([]byte, error) {
	var manifest kernelManifest
	decoder := json.NewDecoder(bytes.NewReader(document))
	if err := decoder.Decode(&manifest); err != nil {
		return nil, err
	}
	if len(manifest.Modules) == 0 {
		return nil, errors.New("CUDA kernel manifest contains no modules")
	}
	var functions []string
	seenNames := make(map[string]struct{})
	seenIDs := make(map[string]string)
	for _, module := range manifest.Modules {
		if !strings.HasSuffix(filepath.ToSlash(module.Asset), "/ops_f32.ptx") {
			continue
		}
		for _, name := range module.Functions {
			if name == "" {
				return nil, errors.New("CUDA kernel manifest contains an empty function")
			}
			if _, duplicate := seenNames[name]; duplicate {
				return nil, fmt.Errorf("CUDA kernel manifest repeats function %q", name)
			}
			identifier := kernelIdentifier(name)
			if previous, collision := seenIDs[identifier]; collision {
				return nil, fmt.Errorf(
					"CUDA kernel functions %q and %q share identifier %q",
					previous, name, identifier,
				)
			}
			seenNames[name] = struct{}{}
			seenIDs[identifier] = name
			functions = append(functions, name)
		}
	}
	if len(functions) == 0 {
		return nil, errors.New("CUDA operation module contains no functions")
	}

	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by cmd/kernel-bindings; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package executor")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, `import "overgo/internal/cuda/driver"`)
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "type kernelFunctionID uint16")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "const (")
	for index, name := range functions {
		assignment := ""
		if index == 0 {
			assignment = " kernelFunctionID = iota"
		}
		fmt.Fprintf(&output, "\t%s%s\n", kernelIdentifier(name), assignment)
	}
	fmt.Fprintln(&output, "\tkernelFunctionCount")
	fmt.Fprintln(&output, ")")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "var kernelFunctionNames = [...]string{")
	for _, name := range functions {
		fmt.Fprintf(&output, "\t%q,\n", name)
	}
	fmt.Fprintln(&output, "}")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "type functionSet [kernelFunctionCount]driver.Function")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "func loadFunctions(lib *driver.Library, module driver.Module) (functionSet, error) {")
	fmt.Fprintln(&output, "\tvar result functionSet")
	fmt.Fprintln(&output, "\tfor id, name := range kernelFunctionNames {")
	fmt.Fprintln(&output, "\t\tfunction, err := lib.ModuleFunction(module, name)")
	fmt.Fprintln(&output, "\t\tif err != nil {")
	fmt.Fprintln(&output, "\t\t\treturn functionSet{}, err")
	fmt.Fprintln(&output, "\t\t}")
	fmt.Fprintln(&output, "\t\tresult[id] = function")
	fmt.Fprintln(&output, "\t}")
	fmt.Fprintln(&output, "\treturn result, nil")
	fmt.Fprintln(&output, "}")
	return format.Source(output.Bytes())
}

func kernelIdentifier(name string) string {
	var result strings.Builder
	result.WriteString("kernel")
	for _, part := range strings.Split(name, "_") {
		if part == "" {
			continue
		}
		result.WriteString(strings.ToUpper(part[:1]))
		result.WriteString(part[1:])
	}
	return result.String()
}
