package codeprofile

import (
	"testing"

	"overgo/internal/repoanalysis"
)

func TestProductionConsumerCensus(t *testing.T) {
	snapshot, err := (repoanalysis.SourceSnapshot{}).Overlay(map[string][]byte{
		"cmd/tool/main.go": []byte("package main\nfunc main() {}\n"),
		"internal/api/api.go": []byte(`package api
type Contract interface { Apply() }
type Message struct { Value string ` + "`json:\"value\"`" + ` }
func Used() {}
func Tested() {}
func Unused() {}
type Worker struct{}
func (Worker) Reflected() {}
//export CEntry
func CEntry() {}
func UseVariant() { Variant() }
`),
		"internal/api/generated.go":       []byte("// Code generated by fixture. DO NOT EDIT.\npackage api\nfunc Generated() {}\n"),
		"internal/api/variant_windows.go": []byte("//go:build windows\npackage api\nfunc Variant() {}\n"),
		"internal/api/variant_linux.go":   []byte("//go:build linux\npackage api\nfunc Variant() {}\n"),
		"internal/api/api_test.go":        []byte("package api\nfunc TestOnly() { Tested() }\n"),
		"internal/testutil/fixture.go":    []byte("package testutil\nfunc Helper() {}\n"),
		"internal/use/use.go":             []byte("package use\nimport a \"example/internal/api\"\nfunc Run() { a.Used() }\n"),
		"internal/reflect/use.go":         []byte("package reflectuse\nimport (\n\t\"reflect\"\n\t\"example/internal/api\"\n)\nfunc Run(v api.Worker) { reflect.ValueOf(v).MethodByName(\"Reflected\") }\n"),
	})
	if err != nil {
		t.Fatal(err)
	}
	selection := repoanalysis.BuildSelection{
		Context: "linux/amd64",
		Files: map[string]bool{
			"cmd/tool/main.go": true, "internal/api/api.go": true, "internal/api/generated.go": true,
			"internal/api/variant_windows.go": false, "internal/api/api_test.go": true,
			"internal/api/variant_linux.go": true,
			"internal/testutil/fixture.go":  true,
			"internal/use/use.go":           true, "internal/reflect/use.go": true,
		},
		Packages: map[string]string{
			"cmd/tool/main.go": "example/cmd/tool", "internal/api/api.go": "example/internal/api",
			"internal/api/generated.go": "example/internal/api", "internal/api/variant_windows.go": "example/internal/api",
			"internal/api/variant_linux.go": "example/internal/api",
			"internal/api/api_test.go":      "example/internal/api", "internal/use/use.go": "example/internal/use",
			"internal/reflect/use.go":      "example/internal/reflect",
			"internal/testutil/fixture.go": "example/internal/testutil",
		},
	}
	declarations, summary, err := ProductionConsumerCensus(snapshot, selection, nil)
	if err != nil {
		t.Fatal(err)
	}
	byName := map[string]ConsumerDeclaration{}
	activeVariant := false
	for _, declaration := range declarations {
		byName[declaration.Name] = declaration
		if declaration.Name == "Variant" && declaration.Boundary == "" && declaration.ProductionReferences > 0 {
			activeVariant = true
		}
	}
	if !activeVariant {
		t.Error("active build variant did not receive its common-file reference")
	}
	for name, want := range map[string]string{
		"main": "command", "Apply": "interface", "Value": "serialization", "Reflected": "reflection",
		"CEntry": "cgo", "Generated": "generated", "Variant": "build-variant", "Helper": "test-helper",
	} {
		if got := byName[name].Boundary; got != want {
			t.Errorf("%s boundary = %q, want %q", name, got, want)
		}
	}
	if byName["Used"].ProductionReferences != 1 || byName["Used"].TestReferences != 0 || byName["Used"].ExternalReferences != 1 {
		t.Errorf("Used = %+v", byName["Used"])
	}
	if byName["Tested"].ProductionReferences != 0 || byName["Tested"].TestReferences != 1 {
		t.Errorf("Tested = %+v", byName["Tested"])
	}
	if byName["Unused"].ProductionReferences != 0 || byName["Unused"].TestReferences != 0 || byName["Unused"].Boundary != "" {
		t.Errorf("Unused = %+v", byName["Unused"])
	}
	if summary.Production == 0 || summary.TestOnly == 0 || summary.Boundary < 6 || summary.Zero == 0 {
		t.Fatalf("summary = %+v", summary)
	}
}

func TestGateRejectsNewUnconsumedProductionSurface(t *testing.T) {
	base := []ConsumerDeclaration{{File: "p.go", Package: "p", Name: "Debt", Kind: "function"}}
	candidate := append([]ConsumerDeclaration(nil), base...)
	candidate = append(candidate,
		ConsumerDeclaration{File: "p.go", Package: "p", Name: "Unused", Kind: "function"},
		ConsumerDeclaration{File: "p.go", Package: "p", Name: "TestOnly", Kind: "function", TestReferences: 1},
		ConsumerDeclaration{File: "p.go", Package: "p", Name: "Used", Kind: "function", ProductionReferences: 1},
		ConsumerDeclaration{File: "p.go", Package: "p", Name: "Init", Kind: "function", Boundary: "command"},
	)
	got := NewUnconsumedSurface(base, candidate)
	if len(got) != 2 || got[0].Name != "Unused" || got[1].Name != "TestOnly" {
		t.Fatalf("new unconsumed surface = %+v", got)
	}
}
