package codeprofile

import (
	"os"
	"path/filepath"
	"testing"

	"overgo/internal/repoanalysis"
)

func TestASTStructuralProfile(t *testing.T) {
	root := t.TempDir()
	for relative, content := range map[string]string{
		"internal/a.go":         "package p\nimport \"fmt\"\nfunc First(v int) int { if v > 0 { fmt.Println(v) }; return v + 1 }\n",
		"internal/b.go":         "package p\nimport \"fmt\"\nfunc second(n int) int { if n > 9 { fmt.Println(n) }; return n + 2 }\n",
		"internal/a_test.go":    "package p\nfunc TestOne(t int) int { return t }\n",
		"internal/generated.go": "// Code generated by fixture. DO NOT EDIT.\npackage p\nfunc Generated() {}\n",
	} {
		path := filepath.Join(root, filepath.FromSlash(relative))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	snapshot, err := repoanalysis.DiscoverGo(root, "internal")
	if err != nil {
		t.Fatal(err)
	}
	profile, err := Build(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	if profile.Production.Files != 2 || profile.Test.Files != 1 || profile.ExportedDeclarations != 1 || profile.PackageImportEdges != 1 {
		t.Fatalf("profile = %+v", profile)
	}
	if len(profile.Clones) != 1 || len(profile.Clones[0].Functions) != 2 || profile.DuplicateExcessNodes == 0 {
		t.Fatalf("clones = %+v", profile.Clones)
	}
	if len(profile.Functions) != 3 || profile.Functions[0].Branches != 1 {
		t.Fatalf("functions = %+v", profile.Functions)
	}
}
