package codeprofile

import (
	"os"
	"path/filepath"
	"testing"

	"overgo/internal/repoanalysis"
)

func TestDomainProfile(t *testing.T) {
	root := t.TempDir()
	for relative, content := range map[string]string{
		"internal/a.go":          "package p\nimport \"fmt\"\nfunc First(v int) int { if v > 0 { fmt.Println(v) }; return v + 1 }\n",
		"internal/b.go":          "package p\nimport \"fmt\"\nfunc second(n int) int { if n > 9 { fmt.Println(n) }; return n + 2 }\n",
		"internal/validate_a.go": "package p\nfunc validateFirst(v int) error { if v > 0 { return nil }; return nil }\n",
		"internal/validate_b.go": "package p\nfunc ValidateSecond(n int) error { if n > 9 { return nil }; return nil }\n",
		"internal/a_test.go":     "package p\nfunc TestOne(t int) int { return t }\n",
		"internal/generated.go":  "// Code generated by fixture. DO NOT EDIT.\npackage p\nfunc Generated() {}\n",
		"cmd/tool/main.go":       "package main\nfunc main() {}\n",
	} {
		path := filepath.Join(root, filepath.FromSlash(relative))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	snapshot, err := repoanalysis.DiscoverGo(root, "internal", "cmd")
	if err != nil {
		t.Fatal(err)
	}
	profile, err := Build(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	expectedRuntimeFiles := len([]string{"internal/a.go", "internal/b.go", "internal/validate_a.go", "internal/validate_b.go"})
	if profile.Runtime.Files != expectedRuntimeFiles || profile.Automation.Files != 1 || profile.Generated.Files != 1 || profile.Test.Files != 1 ||
		profile.ExportedDeclarations != 2 || profile.PackageImportEdges != 1 {
		t.Fatalf("profile = %+v", profile)
	}
	if len(profile.Clones) != 2 || profile.DuplicateExcessNodes == 0 {
		t.Fatalf("clones = %+v", profile.Clones)
	}
	if len(profile.Functions) != 6 || profile.Functions[0].Branches != 1 {
		t.Fatalf("functions = %+v", profile.Functions)
	}
}

func TestAdvisoryCandidate(t *testing.T) {
	root := t.TempDir()
	path := filepath.Join(root, "internal", "signals.go")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte("package p\nfunc work() {}\nfunc validateShape() error { return nil }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	testPath := filepath.Join(root, "internal", "signals_test.go")
	if err := os.WriteFile(testPath, []byte("package p\nfunc TestShape() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	snapshot, err := repoanalysis.DiscoverGo(root, "internal")
	if err != nil {
		t.Fatal(err)
	}
	profile, err := Build(snapshot)
	if err != nil {
		t.Fatal(err)
	}
	classes := map[string]string{}
	for _, function := range profile.Functions {
		classes[function.Name] = function.AdvisoryClass
	}
	if classes["work"] != "" || classes["validateShape"] != "validator" || classes["TestShape"] != "test" {
		t.Fatalf("advisory classes = %v", classes)
	}
}
