package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	manifestPath = "compatibility.yaml"
	matrixPath   = "docs/COMPATIBILITY.md"
)

type manifest struct {
	Schema   int                   `yaml:"schema"`
	Upstream upstream              `yaml:"upstream"`
	Host     host                  `yaml:"host"`
	Go       goRuntime             `yaml:"go"`
	Claims   []claim               `yaml:"claims"`
	Models   map[string]modelClaim `yaml:"models"`
}

type upstream struct {
	Repository string `yaml:"repository"`
	Commit     string `yaml:"commit"`
}

type host struct {
	OS   string `yaml:"os"`
	Arch string `yaml:"arch"`
}

type goRuntime struct {
	Minimum string `yaml:"minimum"`
	CGO     bool   `yaml:"cgo"`
}

type claim struct {
	ID       string     `yaml:"id"`
	Status   string     `yaml:"status"`
	Summary  string     `yaml:"summary"`
	Evidence []evidence `yaml:"evidence"`
}

type evidence struct {
	Path     string `yaml:"path"`
	Contains string `yaml:"contains"`
}

type modelClaim struct {
	Status                     string   `yaml:"status"`
	Execution                  []string `yaml:"execution"`
	Features                   []string `yaml:"features"`
	Limitations                []string `yaml:"limitations"`
	RealModelValidation        any      `yaml:"real_model_validation"`
	ValidatedFixture           string   `yaml:"validated_fixture"`
	AdditionalValidatedFixture string   `yaml:"additional_validated_fixture"`
	MultimodalValidatedFixture string   `yaml:"multimodal_validated_fixture"`
	VideoValidatedFixture      string   `yaml:"video_validated_fixture"`
}

func main() {
	check := flag.Bool("check", false, "verify compatibility claims and generated matrix")
	update := flag.Bool("update", false, "write generated compatibility matrix")
	flag.Parse()
	if flag.NArg() != 0 || *check && *update {
		fmt.Fprintln(os.Stderr, "usage: compatibility [-check|-update]")
		os.Exit(1)
	}
	data, err := generate(".")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if *check {
		current, readErr := os.ReadFile(matrixPath)
		if readErr != nil {
			fmt.Fprintln(os.Stderr, readErr)
			os.Exit(1)
		}
		if !bytes.Equal(current, data) {
			fmt.Fprintln(os.Stderr, "docs/COMPATIBILITY.md is stale; regenerate with: go run ./cmd/compatibility -update")
			os.Exit(1)
		}
		return
	}
	if *update {
		if err := os.WriteFile(matrixPath, data, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		return
	}
	_, _ = os.Stdout.Write(data)
}

func generate(root string) ([]byte, error) {
	document, err := loadManifest(root)
	if err != nil {
		return nil, err
	}
	if err := validateManifest(root, document); err != nil {
		return nil, err
	}
	var output strings.Builder
	output.WriteString("# Compatibility matrix\n\n")
	output.WriteString("Generated from [`compatibility.yaml`](../compatibility.yaml). Do not edit this file directly.\n\n")
	fmt.Fprintf(&output, "Baseline: `%s` at `%s`; host `%s/%s`; Go `%s`; cgo `%t`.\n\n",
		document.Upstream.Repository, document.Upstream.Commit, document.Host.OS,
		document.Host.Arch, document.Go.Minimum, document.Go.CGO)
	output.WriteString("## Verified feature claims\n\n")
	output.WriteString("| ID | State | Claim | Evidence |\n| --- | --- | --- | --- |\n")
	claims := append([]claim(nil), document.Claims...)
	sort.Slice(claims, func(i, j int) bool { return claims[i].ID < claims[j].ID })
	for _, item := range claims {
		links := make([]string, len(item.Evidence))
		for index, proof := range item.Evidence {
			links[index] = fmt.Sprintf("[`%s`](../%s)", proof.Contains, filepath.ToSlash(proof.Path))
		}
		fmt.Fprintf(&output, "| `%s` | %s | %s | %s |\n",
			item.ID, item.Status, escapeCell(item.Summary), strings.Join(links, "<br>"))
	}
	output.WriteString("\n## Model families\n\n")
	output.WriteString("`experimental` means the implementation is guarded by strict metadata/catalog validation but may still lack a local real-model oracle.\n\n")
	output.WriteString("| Model | State | Execution | Real-model validation | Limitations |\n| --- | --- | --- | --- | --- |\n")
	names := make([]string, 0, len(document.Models))
	for name := range document.Models {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		item := document.Models[name]
		execution := strings.Join(item.Execution, ", ")
		if execution == "" {
			execution = "model-dependent"
		}
		validation := modelValidation(item)
		limitations := strings.Join(item.Limitations, ", ")
		if limitations == "" {
			limitations = "-"
		}
		fmt.Fprintf(&output, "| `%s` | %s | %s | %s | %s |\n",
			name, item.Status, escapeCell(execution), escapeCell(validation), escapeCell(limitations))
	}
	return []byte(output.String()), nil
}

func loadManifest(root string) (manifest, error) {
	data, err := os.ReadFile(filepath.Join(root, manifestPath))
	if err != nil {
		return manifest{}, err
	}
	var document manifest
	decoder := yaml.NewDecoder(bytes.NewReader(data))
	if err := decoder.Decode(&document); err != nil {
		return manifest{}, fmt.Errorf("compatibility manifest: %w", err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); err == nil {
		return manifest{}, errors.New("compatibility manifest: multiple YAML documents")
	} else if !errors.Is(err, io.EOF) {
		return manifest{}, fmt.Errorf("compatibility manifest: trailing data: %w", err)
	}
	return document, nil
}

func validateManifest(root string, document manifest) error {
	if document.Schema != 1 || document.Upstream.Repository == "" || len(document.Upstream.Commit) != 40 ||
		document.Host.OS == "" || document.Host.Arch == "" || document.Go.Minimum == "" {
		return errors.New("compatibility manifest: baseline is incomplete")
	}
	if len(document.Claims) == 0 || len(document.Models) == 0 {
		return errors.New("compatibility manifest: claims or models are empty")
	}
	seen := make(map[string]struct{}, len(document.Claims))
	for index, item := range document.Claims {
		if item.ID == "" || item.Summary == "" || (item.Status != "implemented" && item.Status != "partial" && item.Status != "blocked") {
			return fmt.Errorf("compatibility manifest: claim %d is incomplete", index)
		}
		if _, exists := seen[item.ID]; exists {
			return fmt.Errorf("compatibility manifest: duplicate claim %q", item.ID)
		}
		seen[item.ID] = struct{}{}
		hasTest := false
		for _, proof := range item.Evidence {
			if err := validateEvidence(root, item.ID, proof); err != nil {
				return err
			}
			hasTest = hasTest || strings.HasSuffix(proof.Path, "_test.go")
		}
		if len(item.Evidence) == 0 || item.Status == "implemented" && !hasTest {
			return fmt.Errorf("compatibility manifest: claim %q lacks test evidence", item.ID)
		}
	}
	for name, item := range document.Models {
		if name == "" || item.Status == "" || len(item.Features) == 0 {
			return fmt.Errorf("compatibility manifest: model %q is incomplete", name)
		}
	}
	return nil
}

func validateEvidence(root, claimID string, proof evidence) error {
	clean := filepath.Clean(filepath.FromSlash(proof.Path))
	if proof.Path == "" || proof.Contains == "" || filepath.IsAbs(clean) || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
		return fmt.Errorf("compatibility manifest: claim %q has invalid evidence", claimID)
	}
	data, err := os.ReadFile(filepath.Join(root, clean))
	if err != nil {
		return fmt.Errorf("compatibility manifest: claim %q evidence: %w", claimID, err)
	}
	if !bytes.Contains(data, []byte(proof.Contains)) {
		return fmt.Errorf("compatibility manifest: claim %q evidence %q lacks %q", claimID, proof.Path, proof.Contains)
	}
	return nil
}

func scalarText(value any) string {
	if value == nil {
		return "pending-fixture"
	}
	return fmt.Sprint(value)
}

func modelValidation(item modelClaim) string {
	fixtures := []string{
		item.ValidatedFixture,
		item.AdditionalValidatedFixture,
		item.MultimodalValidatedFixture,
		item.VideoValidatedFixture,
	}
	fixtures = slices.DeleteFunc(fixtures, func(value string) bool { return value == "" })
	if len(fixtures) != 0 {
		return "validated: " + strings.Join(fixtures, ", ")
	}
	return scalarText(item.RealModelValidation)
}

func escapeCell(value string) string {
	value = strings.ReplaceAll(value, "|", "\\|")
	value = strings.ReplaceAll(value, "\n", " ")
	return value
}
