package main

import (
	"strings"
	"testing"

	"overgo/internal/overgodb"
	"overgo/internal/recipe"
	"overgo/internal/runrecord"
)

// TestMediaReportRendersStoreTruth pins the generated-report contract:
// an empty store renders the honest empty statement, media-task scope
// excludes text tasks, and a claim cell states tier, measurements, and
// commit -- or the honest dash when no verification stands.
func TestMediaReportRendersStoreTruth(t *testing.T) {
	root := t.TempDir()
	store, err := overgodb.Open(root + "/store")
	if err != nil {
		t.Fatal(err)
	}
	if err := store.Close(); err != nil {
		t.Fatal(err)
	}
	writeTestManifest(t, root, []claim{}, testModels())
	data, err := generateMediaReport(root, root+"/store")
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	if !strings.Contains(text, "No media activations stand in the store.") ||
		!strings.Contains(text, "Do not edit this file directly.") {
		t.Fatalf("empty-store report:\n%s", text)
	}
	if !strings.Contains(text, "## Measured results") ||
		!strings.Contains(text, "No healthy activation carries a readable run record.") {
		t.Fatalf("measured-results section absent on the empty store:\n%s", text)
	}

	if mediaTask(recipe.TaskInference) || mediaTask(recipe.TaskTraining) || !mediaTask(recipe.TaskImageGen) || !mediaTask(recipe.TaskSpeech) {
		t.Fatal("media scope admits text tasks or drops media tasks")
	}

	claims := []runrecord.CapabilityClaim{{
		Capability: "image-gen", Tier: runrecord.TierRealArtifactSmoke,
		Commit: strings.Repeat("ab", 20), WallNS: 1500000000, PeakDeviceBytes: 42,
	}}
	cell := claimCell(claims, recipe.TaskImageGen)
	if !strings.Contains(cell, "real-artifact-smoke") || !strings.Contains(cell, "1.5s") ||
		!strings.Contains(cell, "42 B peak") || !strings.Contains(cell, "abababababab") {
		t.Fatalf("claim cell = %q", cell)
	}
	if claimCell(claims, recipe.TaskVideoGen) != "-" {
		t.Fatal("an absent claim must render the honest dash")
	}
	if staleCell("") != "-" || !strings.Contains(staleCell("no policy"), "stale: no policy") {
		t.Fatal("stale cell contract")
	}
}
