package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"overgo/internal/artifact"
	"overgo/internal/gitauthority"
	"overgo/internal/jsonfile"
	"overgo/internal/testevidence"
)

const mediaValidationPath = "docs/image_video_validation.json"

// mediaValidationIndex locates acquired test output. Verdicts come from the
// existing Go test evidence parser; scope descriptions are not acceptance.
type mediaValidationIndex struct {
	Version     uint16                 `json:"version"`
	Source      string                 `json:"source_base"`
	Environment string                 `json:"environment"`
	Notes       []string               `json:"notes"`
	Checks      []mediaValidationCheck `json:"checks"`
}

type mediaValidationCheck struct {
	Name        string                 `json:"name"`
	Evidence    artifact.ID            `json:"evidence"`
	Command     string                 `json:"command"`
	Scope       string                 `json:"scope"`
	SourceFiles map[string]string      `json:"changed_source_sha256,omitempty"`
	Harness     map[string]artifact.ID `json:"overlay_sources,omitempty"`
}

func mediaValidationVerdict(data []byte) string {
	report, err := testevidence.GoTestJSONReport(string(data))
	if err != nil {
		return "Invalid evidence: " + err.Error()
	}
	if err := testevidence.RequireComplete(report); err != nil {
		return "Not passed: " + err.Error()
	}
	if report.PassedTests == 0 || report.PassedPackages == 0 {
		return "Unavailable: no completed test assertions"
	}
	return "Passed selected tests"
}

func writeMediaValidation(ctx context.Context, output *bytes.Buffer, root string, reader artifact.Reader) error {
	output.WriteString("## Current validation checkpoint\n\n")
	var index mediaValidationIndex
	if err := jsonfile.Decode(filepath.Join(root, mediaValidationPath), &index); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			output.WriteString("No current validation index is recorded.\n\n")
			return nil
		}
		return err
	}
	if index.Version != 1 || !gitauthority.ValidObjectID(index.Source) || index.Environment == "" || len(index.Checks) == 0 {
		return errors.New("media validation: incomplete checkpoint identity")
	}
	fmt.Fprintf(output, "Selected tests executed against source base `%s` and the per-check source changes recorded in the [validation index](%s). This checkpoint does not complete the campaign.\n\n%s\n\n", index.Source, mediaValidationPath, index.Environment)
	for _, note := range index.Notes {
		fmt.Fprintf(output, "%s\n\n", note)
	}
	output.WriteString("| Check | Recorded result | Scope and observations | Evidence |\n| --- | --- | --- | --- |\n")
	seen := map[string]bool{}
	for _, check := range index.Checks {
		if check.Name == "" || seen[check.Name] || check.Scope == "" || check.Command == "" || check.Evidence.Kind() != artifact.KindEvidence {
			return errors.New("media validation: invalid or duplicate check")
		}
		seen[check.Name] = true
		content, found, err := artifact.ReadContent(ctx, reader, check.Evidence)
		verdict := "Unavailable: evidence content absent"
		if err != nil {
			verdict = "Invalid evidence: " + err.Error()
		} else if found {
			verdict = mediaValidationVerdict(content.Data)
		}
		fmt.Fprintf(output, "| %s | %s | %s | `%s` |\n", escapeMarkdown(check.Name), escapeMarkdown(verdict), escapeMarkdown(check.Scope), check.Evidence)
	}
	output.WriteString("\nResults describe the selected tests, including failures, rather than all supported requests. Commands and retained overlay sources in the index identify each acquisition. Test output is stored by content identity in OvergoDB.\n\n")
	output.WriteString("The samples below come from earlier stored runs. Their original source and environment fields remain unchanged. Historical GIFs retain their original timing; they have not been regenerated by this checkpoint.\n\n")
	return nil
}
