package main

import (
	"bytes"
	"cmp"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"time"

	"overgo/internal/artifact"
	"overgo/internal/discovery"
	"overgo/internal/modelrecipe"
	"overgo/internal/overgodb"
	"overgo/internal/recipe"
	"overgo/internal/runrecord"
)

// The media report is the generated counterpart of a hand-written
// validation report: every media-task activation the store holds --
// speech, image and video generation, video edit, vision QA -- joined
// with the typed verification claims that measured it. Nothing is
// asserted the store does not record; a hand-written verdict never
// enters a generated projection.
const mediaReportPath = "docs/MEDIA_REPORT.md"

// mediaTasks are the report's scope: output-producing media
// capabilities, in ladder order.
// mediaCatalogLimit bounds the catalog read far above the local model
// population; truncation is reported in the output rather than hidden.
const mediaCatalogLimit = 4096

var mediaTasks = []recipe.Task{
	recipe.TaskSpeech, recipe.TaskImageGen, recipe.TaskVideoGen, recipe.TaskVideoEdit, recipe.TaskVQA,
}

// reportRow is one media activation row joined with its claim.
type reportRow struct {
	model, task, tier, stale, claim string
	modelID                         artifact.ID
}

// generateMediaReport renders every media activation with its
// verification evidence. Models without any media task are absent;
// stale activations are reported as stale, never hidden.
func generateMediaReport(root, repository string) ([]byte, error) {
	store, err := overgodb.OpenReadOnly(repository)
	if err != nil {
		return nil, err
	}
	defer store.Close()
	ctx := context.Background()
	entries, truncated, err := discovery.CapabilityCatalog(ctx, store, mediaCatalogLimit, nil)
	if err != nil {
		return nil, err
	}
	inventory, err := loadVerificationInventory(root)
	if err != nil {
		return nil, err
	}
	claimsByModel := map[artifact.ID][]runrecord.CapabilityClaim{}
	namesByModel := map[artifact.ID]string{}
	for _, row := range inventory.Rows {
		claimsByModel[row.Model] = row.Capabilities
		namesByModel[row.Model] = row.Name
	}
	var output bytes.Buffer
	output.WriteString("# Media capability report\n\n")
	output.WriteString("Generated by `go run ./cmd/compatibility -update-media` from the OvergoDB store and the typed verification specifications under `docs/verification`. Do not edit this file directly.\n\n")
	output.WriteString("Evidence rules: an activation states its recipe evidence tier; a measured claim states its verification tier, commit, and measurements; a stale activation is reported as stale, never served, never hidden. Absence of a claim row means no measured verification stands for that task.\n\n")
	writeMediaVerdict(ctx, &output, store, entries)
	writeMediaSurface(&output)
	output.WriteString("## Media activations\n\n")
	output.WriteString("| Model | Task | Activation tier | Stale | Measured claim |\n| --- | --- | --- | --- | --- |\n")
	var report []reportRow
	for _, entry := range entries {
		for _, capability := range entry.Capabilities {
			if !mediaTask(capability.Task) {
				continue
			}
			name := namesByModel[entry.Model]
			if name == "" && entry.Location != "" {
				name = mediaModelName(entry.Location)
			}
			if name == "" {
				name = entry.Model.String()
			}
			report = append(report, reportRow{
				model: name, task: string(capability.Task), tier: string(capability.Tier), modelID: entry.Model,
				stale: staleCell(capability.Stale),
				claim: claimCell(claimsByModel[entry.Model], capability.Task),
			})
		}
	}
	sort.Slice(report, func(i, j int) bool {
		if report[i].model != report[j].model {
			return report[i].model < report[j].model
		}
		return report[i].task < report[j].task
	})
	for _, row := range report {
		fmt.Fprintf(&output, "| `%s` | `%s` | %s | %s | %s |\n",
			escapeMarkdown(row.model), row.task, row.tier, row.stale, row.claim)
	}
	if len(report) == 0 {
		output.WriteString("\nNo media activations stand in the store.\n")
	}
	if truncated {
		output.WriteString("\nThe capability listing was truncated; this report is incomplete and says so.\n")
	}
	output.WriteString("\nThe matrix reports activation and evidence scope, not general model-family support: an activation means the recipe lifecycle admitted the model for the task at the stated tier, and a measured claim binds that capability to real execution evidence at its commit.\n\n")
	writeMediaInventories(ctx, &output, store, report)
	output.WriteString("## Measured results\n\n")
	output.WriteString("One row per healthy activation: the verifier run the activation cites, exactly as recorded -- wall, measured phase decomposition, peak device bytes, verifying commit, and the output artifacts the run published. A dash means the activation stands without that measurement.\n\n")
	output.WriteString("| Model | Task | Verifier wall | Phases | Peak device | Commit | Run outputs |\n| --- | --- | --- | --- | --- | --- | --- |\n")
	results := 0
	for _, row := range report {
		if strings.HasPrefix(row.stale, "stale") {
			continue
		}
		measured := activationRunResult(ctx, store, row.modelID, recipe.Task(row.task))
		fmt.Fprintf(&output, "| `%s` | `%s` | %s |\n", escapeMarkdown(row.model), row.task, measured)
		results++
	}
	if results == 0 {
		output.WriteString("\nNo healthy activation carries a readable run record.\n")
	}
	if err := writeMediaSamplesSection(ctx, &output, store, root, entries); err != nil {
		return nil, err
	}
	return output.Bytes(), nil
}

// writeMediaVerdict computes the report's verdict from the store: how
// many media activations stand, how many are stale, and how many carry
// a measured phase decomposition. Nothing here is hand-written.
func writeMediaVerdict(ctx context.Context, output *bytes.Buffer, store *overgodb.Store, entries []discovery.CatalogEntry) {
	activations, stale, measured := 0, 0, 0
	for _, entry := range entries {
		for _, capability := range entry.Capabilities {
			if !mediaTask(capability.Task) {
				continue
			}
			activations++
			if capability.Stale != "" {
				stale++
				continue
			}
			if cell := activationRunResult(ctx, store, entry.Model, capability.Task); !strings.HasPrefix(cell, "- |") {
				measured++
			}
		}
	}
	output.WriteString("## Verdict\n\n")
	if activations == 0 {
		output.WriteString("No media activations stand in the store; there is nothing to serve.\n\n")
		return
	}
	fmt.Fprintf(output,
		"The store holds %d media activations across speech, image generation, video generation, video edit, and vision QA; %d are stale and %d healthy activations cite a readable measured verifier run. Every claim below is a projection of store evidence at its recorded commit.\n\n",
		activations, stale, measured)
}

// writeMediaSurface renders the public entry points every media
// capability shares: the task-generic recipe lifecycle CLI. The rows
// restate the command contract, not per-model knowledge.
func writeMediaSurface(output *bytes.Buffer) {
	output.WriteString("## Public media surface\n\n")
	output.WriteString("Every media capability is exercised through the same task-generic recipe lifecycle; requests are typed JSON on standard input and outputs are typed store artifacts.\n\n")
	output.WriteString("| Operation | Command |\n| --- | --- |\n")
	for _, row := range [][2]string{
		{"Verify (candidate execution + gate/run evidence)", "`go run ./cmd/recipe verify -task <task> -repo <overgodb> -input - <model-path> < request.json`"},
		{"Activate (bind verified evidence to the active alias)", "`go run ./cmd/recipe activate -task <task> -repo <overgodb> -gate <id> -run-id <id> -reason <why> <model-path>`"},
		{"Run (serve through the active recipe)", "`go run ./cmd/recipe run -task <task> -repo <overgodb> -input - <model-path> < request.json`"},
		{"Report (this document)", "`go run ./cmd/compatibility -update-media`"},
		{"Sample export (decoded verifier outputs)", "`go run ./cmd/compatibility -export-samples`"},
	} {
		fmt.Fprintf(output, "| %s | %s |\n", row[0], row[1])
	}
	output.WriteString("\nMedia tasks: `speech`, `image-gen`, `video-gen`, `video-edit`, `vqa`. The VQA lane verifies and activates through `go run ./cmd/vqaparity -recipe-verify-activate`.\n\n")
}

// writeMediaInventories renders the compiled recipe graphs behind the
// healthy activations: per activation, the recipe identity and its
// node/module/placement decomposition, straight from the stored
// definitions.
func writeMediaInventories(
	ctx context.Context,
	output *bytes.Buffer,
	store *overgodb.Store,
	rows []reportRow,
) {
	output.WriteString("## Function inventory\n\n")
	output.WriteString("The executable surface behind each healthy activation: every recipe node with its module and placement, from the activation's own stored definition. Modules are the native Go implementations the workflow runtime binds.\n\n")
	output.WriteString("| Model | Task | Node | Module | Placement | Session | Component model |\n| --- | --- | --- | --- | --- | --- | --- |\n")
	nodes := 0
	output2 := &bytes.Buffer{}
	output2.WriteString("## Recipe inventory\n\n")
	output2.WriteString("One row per healthy activation: the recipe artifact the active alias resolves, its evidence tier, and its non-model dependencies.\n\n")
	output2.WriteString("| Model | Task | Recipe | Evidence tier | Dependencies |\n| --- | --- | --- | --- | --- |\n")
	recipes := 0
	for _, row := range rows {
		if strings.HasPrefix(row.stale, "stale") {
			continue
		}
		activation, active, err := modelrecipe.ActiveRecord(ctx, store, row.modelID, recipe.Task(row.task))
		if err != nil || !active {
			continue
		}
		for _, node := range activation.Definition.Nodes {
			session := string(node.Session)
			session = cmp.Or(session, "-")
			// A slotted node states the content-identified component model
			// it executes against; a shared component (a Flux-lineage VAE,
			// for example) renders the same identity wherever it appears.
			component := "composite"
			if node.ModelSlot != 0 {
				if model, ok := activation.Definition.Dependency(recipe.DependencyModel, node.ModelSlot); ok {
					component = "`" + shortArtifact(model) + "`"
				}
			}
			fmt.Fprintf(output, "| `%s` | `%s` | `%s` | `%s` | %s | %s | %s |\n",
				escapeMarkdown(row.model), row.task, node.ID, node.Module, node.Placement, session, component)
			nodes++
		}
		dependencies := make([]string, 0, len(activation.Definition.Dependencies))
		for _, dependency := range activation.Definition.Dependencies {
			if dependency.Role == recipe.DependencyModel {
				continue
			}
			dependencies = append(dependencies, fmt.Sprintf("%s `%s`", dependency.Role, shortArtifact(dependency.Artifact)))
		}
		rendered := "-"
		if len(dependencies) > 0 {
			rendered = strings.Join(dependencies, ", ")
		}
		fmt.Fprintf(output2, "| `%s` | `%s` | `%s` | %s | %s |\n",
			escapeMarkdown(row.model), row.task, shortArtifact(activation.Definition.ID), activation.Tier, rendered)
		recipes++
	}
	if nodes == 0 {
		output.WriteString("\nNo healthy activation stands; the inventory is empty.\n")
	}
	if recipes == 0 {
		output2.WriteString("\nNo healthy activation stands; the inventory is empty.\n")
	}
	output.WriteString("\n")
	output.Write(output2.Bytes())
	output.WriteString("\n")
}

// writeMediaSamplesSection links the exported verifier-run outputs
// under docs/media_samples: images and clips embed inline, audio links
// as playable WAV. Only files that exist on disk are linked, and each
// is named by its content SHA-256 so it is checkable against the run
// that produced it.
func writeMediaSamplesSection(
	ctx context.Context,
	output *bytes.Buffer,
	store *overgodb.Store,
	root string,
	entries []discovery.CatalogEntry,
) error {
	output.WriteString("\n## Samples\n\n")
	output.WriteString("Decoded verifier-run outputs, exported by `go run ./cmd/compatibility -export-samples` and named by content SHA-256. Every sample is a real output of a succeeded verification run recorded in the store.\n\n")
	directory := filepath.Join(root, mediaSamplesDir)
	linked := 0
	for _, entry := range entries {
		for _, capability := range entry.Capabilities {
			if !mediaTask(capability.Task) || capability.Stale != "" {
				continue
			}
			activation, active, err := modelrecipe.ActiveRecord(ctx, store, entry.Model, capability.Task)
			if err != nil || !active {
				continue
			}
			samples, err := recipeSampleNames(ctx, store, activation.Definition.ID)
			if err != nil {
				return err
			}
			present := make([]sampleRef, 0, len(samples))
			for _, sample := range samples {
				if _, statErr := os.Stat(filepath.Join(directory, sample.Name)); statErr == nil {
					present = append(present, sample)
				}
			}
			if len(present) == 0 {
				continue
			}
			name := mediaModelName(entry.Location)
			if name == "" {
				name = entry.Model.String()
			}
			fmt.Fprintf(output, "### %s (`%s`)\n\n", escapeMarkdown(name), capability.Task)
			for _, sample := range present {
				relative := "media_samples/" + sample.Name
				switch {
				case strings.HasSuffix(sample.Name, ".wav"):
					fmt.Fprintf(output, "- Audio clip: [%s](%s)\n", sample.Name, relative)
				case strings.HasSuffix(sample.Name, ".gif"):
					fmt.Fprintf(output, "- Video clip: [%s](%s)\n\n  ![%s clip](%s)\n", sample.Name, relative, escapeMarkdown(name), relative)
				default:
					fmt.Fprintf(output, "- Image: [%s](%s)\n\n  ![%s image](%s)\n", sample.Name, relative, escapeMarkdown(name), relative)
				}
				if sample.Request != "" {
					fmt.Fprintf(output, "\n  Request: `%s`\n", sample.Request)
				}
				linked++
			}
			output.WriteString("\n")
		}
	}
	if linked == 0 {
		output.WriteString("No exported samples are present on disk; run the sample export first.\n")
	}
	return nil
}

func shortArtifact(id artifact.ID) string {
	rendered := id.String()
	if len(rendered) > 32 {
		return rendered[:32]
	}
	return rendered
}

// activationRunResult reads the run the activation's own evidence
// cites and renders its measurements; absence renders dashes, never an
// invented number.
func activationRunResult(ctx context.Context, store *overgodb.Store, model artifact.ID, task recipe.Task) string {
	activation, active, err := modelrecipe.ActiveRecord(ctx, store, model, task)
	if err != nil || !active {
		return "- | - | - | - | -"
	}
	peak := activationPeakDeviceBytes(ctx, store, activation.Event.Evidence)
	for _, evidence := range activation.Event.Evidence {
		if evidence.Kind() != artifact.KindRun {
			continue
		}
		content, found, err := artifact.ReadContent(ctx, store, evidence)
		if err != nil || !found {
			continue
		}
		run, err := runrecord.ParseRun(content.Data)
		if err != nil {
			continue
		}
		outputs := make([]string, 0, len(run.Outputs))
		for _, output := range run.Outputs {
			outputs = append(outputs, "`"+output.String()[:32]+"`")
		}
		rendered := "-"
		if len(outputs) > 0 {
			rendered = strings.Join(outputs, ", ")
		}
		return fmt.Sprintf("%s | %s | %s | `%s` | %s",
			time.Duration(run.MeasuredNS).Round(time.Millisecond).String(),
			phaseCell(run.Phases), peak, shortCommit(run.CodeCommit), rendered)
	}
	return "- | - | " + peak + " | - | -"
}

// mediaRunPhases is the report's phase scope: the measured recipe-node
// decomposition, excluding the gate's own bookkeeping phases whose
// totals duplicate the wall column.
var mediaRunPhases = map[runrecord.Phase]bool{
	runrecord.PhasePrepare: true, runrecord.PhaseIntegrate: true,
	runrecord.PhaseDecode: true, runrecord.PhaseGenerate: true,
	runrecord.PhaseTokenize: true,
}

// phaseCell renders the run's recorded node-phase walls in recorded
// order, or the honest dash when the run predates phase capture.
func phaseCell(phases []runrecord.PhaseMetric) string {
	parts := make([]string, 0, len(phases))
	for _, metric := range phases {
		if !mediaRunPhases[metric.Phase] {
			continue
		}
		parts = append(parts, fmt.Sprintf("%s %s",
			metric.Phase, time.Duration(metric.DurationNS).Round(time.Millisecond)))
	}
	if len(parts) == 0 {
		return "-"
	}
	return strings.Join(parts, ", ")
}

// activationPeakDeviceBytes reads the gate result the activation cites
// and extracts the recorded peak-device evidence; absence renders the
// dash, never an invented number.
func activationPeakDeviceBytes(ctx context.Context, store *overgodb.Store, evidence []artifact.ID) string {
	for _, id := range evidence {
		if id.Kind() != artifact.KindEvidence {
			continue
		}
		content, found, err := artifact.ReadContent(ctx, store, id)
		if err != nil || !found {
			continue
		}
		gate, err := runrecord.ParseGateResult(content.Data)
		if err != nil {
			continue
		}
		for _, step := range gate.Steps {
			if peak, ok := stepPeakDeviceBytes(step.Evidence); ok {
				return peak
			}
		}
	}
	return "-"
}

// stepPeakDeviceBytes parses the peak_device_bytes evidence marker a
// measured verification writes into its execution step.
func stepPeakDeviceBytes(evidence string) (string, bool) {
	const marker = "peak_device_bytes="
	index := strings.Index(evidence, marker)
	if index < 0 {
		return "", false
	}
	digits := evidence[index+len(marker):]
	end := 0
	for end < len(digits) && digits[end] >= '0' && digits[end] <= '9' {
		end++
	}
	if end == 0 {
		return "", false
	}
	return digits[:end] + " B", true
}

// mediaModelName derives a distinctive name from a recorded location:
// the deepest path segment that is not a generic weights file or a
// standard repository component directory. The skipped names are
// format facts of the HF and diffusers layouts, not model knowledge.
func mediaModelName(location string) string {
	generic := map[string]bool{
		"text_encoder": true, "transformer": true, "vae": true,
		"scheduler": true, "tokenizer": true,
		"classification": true, "regression": true,
	}
	segments := strings.Split(filepath.ToSlash(location), "/")
	for index := len(segments) - 1; index >= 0; index-- {
		segment := segments[index]
		lower := strings.ToLower(segment)
		if strings.HasSuffix(lower, ".safetensors") || strings.HasSuffix(lower, ".gguf") ||
			strings.HasSuffix(lower, ".pt") || generic[lower] {
			continue
		}
		return segment
	}
	return filepath.Base(location)
}

func mediaTask(task recipe.Task) bool {
	return slices.Contains(mediaTasks, task)
}

func staleCell(stale string) string {
	if stale == "" {
		return "-"
	}
	return "stale: " + escapeMarkdown(stale)
}

// claimCell renders the strongest verification claim recorded for the
// capability, or the honest dash when none stands.
func claimCell(claims []runrecord.CapabilityClaim, task recipe.Task) string {
	for _, claim := range claims {
		if claim.Capability != string(task) {
			continue
		}
		parts := []string{string(claim.Tier)}
		if measured(claim.WallNS) {
			parts = append(parts, time.Duration(claim.WallNS).Round(time.Millisecond).String())
		}
		if measured(claim.PeakDeviceBytes) {
			parts = append(parts, fmt.Sprintf("%d B peak", claim.PeakDeviceBytes))
		}
		parts = append(parts, "`"+shortCommit(claim.Commit)+"`")
		return strings.Join(parts, ", ")
	}
	return "-"
}

func shortCommit(commit string) string {
	if len(commit) > 12 {
		return commit[:12]
	}
	return commit
}
