package main

import (
	"bytes"
	"cmp"
	"context"
	"errors"
	"fmt"
	"path/filepath"
	"slices"
	"strings"
	"time"

	"overgo/internal/artifact"
	"overgo/internal/discovery"
	"overgo/internal/modelrecipe"
	"overgo/internal/overgodb"
	"overgo/internal/recipe"
	"overgo/internal/runrecord"
)

// The media report is the generated counterpart of a hand-written
// validation report: every media-task activation the store holds --
// speech, image and video generation, video edit, vision QA -- joined
// with the typed verification claims that measured it. Nothing is
// asserted the store does not record; a hand-written verdict never
// enters a generated projection.
const mediaReportPath = "docs/MEDIA_REPORT.md"

type mediaReportScope struct {
	Tasks          []recipe.Task
	FrozenRequests bool
}

func resolveMediaReportScope(name string) (mediaReportScope, error) {
	switch name {
	case "all":
		return mediaReportScope{Tasks: mediaTasks}, nil
	case "image-video":
		return mediaReportScope{Tasks: []recipe.Task{recipe.TaskImageGen, recipe.TaskVideoGen}, FrozenRequests: true}, nil
	default:
		return mediaReportScope{}, errors.New("media scope must be all or image-video")
	}
}

// mediaTasks are the report's scope: output-producing media
// capabilities, in ladder order.
// mediaCatalogLimit bounds the catalog read far above the local model
// population; truncation is reported in the output rather than hidden.
const mediaCatalogLimit = 4096

var mediaTasks = []recipe.Task{
	recipe.TaskSpeech, recipe.TaskImageGen, recipe.TaskVideoGen, recipe.TaskVQA,
}

// reportRow is one media activation row joined with its claim.
type reportRow struct {
	model, task, tier, stale, claim string
	modelID                         artifact.ID
	activation                      modelrecipe.Activation
	verification                    runrecord.Verification
}

// generateMediaReport renders every media activation with its
// verification evidence. Models without any media task are absent;
// stale activations are reported as stale, never hidden.
func generateMediaReport(root, repository string) ([]byte, error) {
	scope := mediaReportScope{Tasks: mediaTasks}
	store, err := overgodb.OpenReadOnly(repository)
	if err != nil {
		return nil, err
	}
	defer store.Close()
	ctx := context.Background()
	entries, truncated, err := discovery.CapabilityCatalogForTasks(ctx, store, mediaCatalogLimit, discovery.LoadMemo(ctx, store), scope.Tasks...)
	if err != nil {
		return nil, err
	}
	inventory, err := loadVerificationInventory(root)
	if err != nil {
		return nil, err
	}
	claimsByModel := map[artifact.ID][]runrecord.CapabilityClaim{}
	namesByModel := map[artifact.ID]string{}
	for _, row := range inventory.Rows {
		claimsByModel[row.Model] = row.Capabilities
		namesByModel[row.Model] = row.Name
	}
	report, err := loadMediaReportRows(ctx, store, entries, scope, claimsByModel, namesByModel)
	if err != nil {
		return nil, err
	}
	var output bytes.Buffer
	output.WriteString("# Media capability report\n\nGenerated by `go run ./cmd/compatibility -update-media` from OvergoDB and the typed verification specifications. Do not edit this file directly.\n\n")
	output.WriteString("Activation records identify available recipes. Verification records identify the source and measurements they actually captured. Neither establishes visual quality or a matched optimization comparison by itself. Missing evidence remains unavailable.\n\n")
	if err := writeMediaValidation(ctx, &output, root, store); err != nil {
		return nil, err
	}
	writeImageVideoReportRequirements(&output)
	writeMediaVerdict(&output, report, scope)
	writeMediaSurface(&output)
	output.WriteString("## Media activations\n\n")
	output.WriteString("| Model | Task | Activation tier | Stale | Measured claim |\n| --- | --- | --- | --- | --- |\n")
	for _, row := range report {
		fmt.Fprintf(&output, "| `%s` | `%s` | %s | %s | %s |\n",
			escapeMarkdown(row.model), row.task, row.tier, staleCell(row.stale), row.claim)
	}
	if len(report) == 0 {
		output.WriteString("\nNo media activations stand in the store.\n")
	}
	if truncated {
		output.WriteString("\nThe capability listing was truncated; this report is incomplete and says so.\n")
	}
	output.WriteString("\nThe matrix reports activation and evidence scope, not general model-family support: an activation means the recipe lifecycle admitted the model for the task at the stated tier, and a measured claim binds that capability to real execution evidence at its commit.\n\n")
	writeMediaInventories(&output, report)
	output.WriteString("## Measured results\n\n")
	output.WriteString("One row per healthy activation: the verifier run the activation cites, exactly as recorded -- wall, measured phase decomposition, peak device bytes, verifying commit, and the output artifacts the run published. A dash means the activation stands without that measurement.\n\n")
	output.WriteString("| Model | Task | Verifier wall | Phases | Peak device | Commit | Run outputs |\n| --- | --- | --- | --- | --- | --- | --- |\n")
	results := 0
	for _, row := range report {
		if !row.verification.Run.ID.Valid() {
			continue
		}
		measured := mediaRunResult(row.verification)
		fmt.Fprintf(&output, "| `%s` | `%s` | %s |\n", escapeMarkdown(row.model), row.task, measured)
		results++
	}
	if results == 0 {
		output.WriteString("\nNo healthy activation carries a readable run record.\n")
	}
	output.WriteString("\n## Recorded run outcomes\n\nThese counts include generation and verification records for the selected recipes. They are not counts of images or quality passes. Failed and cancelled attempts remain visible.\n\n")
	for _, row := range report {
		if row.stale != "" {
			continue
		}
		fmt.Fprintf(&output, "### %s (%s)\n\n", escapeMarkdown(row.model), row.task)
		if err := writeRecipeRunOutcomes(ctx, &output, store, row.activation.Definition.ID); err != nil {
			return nil, err
		}
	}
	if err := writeMediaSamplesSection(ctx, &output, store, root, report); err != nil {
		return nil, err
	}
	return append(bytes.TrimRight(output.Bytes(), "\n"), '\n'), nil
}

// Resolve each row once; renderers share its exact activation and verifier pair.
func loadMediaReportRows(ctx context.Context, store artifact.Reader, entries []discovery.CatalogEntry, scope mediaReportScope, claims map[artifact.ID][]runrecord.CapabilityClaim, names map[artifact.ID]string) ([]reportRow, error) {
	var rows []reportRow
	for _, entry := range entries {
		for _, capability := range entry.Capabilities {
			if !slices.Contains(scope.Tasks, capability.Task) {
				continue
			}
			name := names[entry.Model]
			if name == "" && entry.Location != "" {
				name = mediaModelName(entry.Location)
			}
			row := reportRow{model: cmp.Or(name, entry.Model.String()), modelID: entry.Model,
				task: string(capability.Task), tier: string(capability.Tier), stale: capability.Stale,
				claim: claimCell(claims[entry.Model], capability.Task)}
			if row.stale == "" {
				active, found, err := modelrecipe.ActiveRecord(ctx, store, entry.Model, capability.Task)
				if err == nil && !found {
					err = errors.New("activation absent")
				}
				if err == nil && active.Definition.ID != capability.Recipe {
					err = errors.New("activation differs from selected recipe")
				}
				if err == nil {
					row.verification, err = runrecord.VerifyEvidence(ctx, store, active.Definition.ID, active.Event.Evidence)
				}
				if err != nil {
					if ctx.Err() != nil {
						return nil, ctx.Err()
					}
					row.stale = err.Error()
				} else {
					row.activation = active
				}
			}
			rows = append(rows, row)
		}
	}
	slices.SortFunc(rows, func(left, right reportRow) int {
		if left.model != right.model {
			return cmp.Compare(left.model, right.model)
		}
		if left.modelID != right.modelID {
			return artifact.CompareID(left.modelID, right.modelID)
		}
		return cmp.Compare(left.task, right.task)
	})
	return rows, nil
}

func writeImageVideoReportRequirements(output *bytes.Buffer) {
	output.WriteString("## Campaign requirements\n\nThe [quality protocol](image_video_protocol.json), [resource protocol](image_video_resources.json), and [execution plan](plan.json) define the required comparisons. This projection of activation and run records remains incomplete as a campaign result until those checks and their exact evidence are joined.\n\n")
	output.WriteString("| Area | Required report evidence |\n| --- | --- |\n")
	for _, row := range [][2]string{
		{"Identity", "Model, recipe, reference, criteria, complete request, source revision, environment, run, and output identities"},
		{"Correctness and quality", "Separate numerical, structural, visual and temporal outcomes; retain failures, unavailable checks and reference limitations"},
		{"Processing", "Matched cold/warm preparation, integration, decode, serialization, export, cleanup and total wall; include waiting and failed attempts"},
		{"Transfers", "HtoD, DtoH and DtoD bytes and calls by weight, conditioning, latent, intermediate, output and diagnostic boundary; synchronization and wait observations"},
		{"Memory", "Process host peak, Go allocations, pinned host storage, driver-owned live/peak bytes, retained session memory and current capacity as distinct scopes"},
		{"Shared code", "Original and replacement owners, real migrated consumers, removed duplicate paths, and added code"},
		{"Reliability and workflows", "Cancellation, release, repeated and changed shapes, restart/reuse, API and workbench receipts"},
		{"Decision", "Matched baseline/candidate measurements and protocol identities, accepted or rejected changes, tradeoffs, and combined validation"},
	} {
		fmt.Fprintf(output, "| %s | %s |\n", row[0], row[1])
	}
	output.WriteString("\nMissing measurements remain unavailable; a reported zero requires an observation. Historical verifier timings and separate generation outputs do not form a matched performance result without an execution-specific link.\n\n")
}

func writeRecipeRunOutcomes(ctx context.Context, output *bytes.Buffer, store *overgodb.Store, definition artifact.ID) error {
	counts := map[runrecord.Outcome]int{}
	var negative bytes.Buffer
	err := visitRecipeRuns(ctx, store, definition, func(run runrecord.Run) error {
		counts[run.Outcome]++
		if run.Outcome != runrecord.OutcomeSucceeded {
			fmt.Fprintf(&negative, "- `%s`: %s; %s. Source: %s. Environment: %s.\n", run.ID, run.Outcome, escapeMarkdown(run.Failure), mediaEvidenceCell(run.CodeCommit), mediaEvidenceCell(run.Environment.String()))
		}
		return nil
	})
	if err != nil {
		return err
	}
	fmt.Fprintf(output, "Succeeded: %d; failed: %d; cancelled: %d.\n\n", counts[runrecord.OutcomeSucceeded], counts[runrecord.OutcomeFailed], counts[runrecord.OutcomeCancelled])
	if negative.Len() > 0 {
		output.Write(negative.Bytes())
		output.WriteString("\n")
	}
	return nil
}

// writeMediaVerdict computes the report's verdict from the store: how
// many media activations stand, how many are stale, and how many carry
// a measured phase decomposition. Nothing here is hand-written.
func writeMediaVerdict(output *bytes.Buffer, rows []reportRow, scope mediaReportScope) {
	activations, stale, measured := len(rows), 0, 0
	for _, row := range rows {
		if row.stale != "" {
			stale++
		}
		if row.verification.Run.ID.Valid() {
			measured++
		}
	}
	output.WriteString("## Verdict\n\n")
	if activations == 0 {
		output.WriteString("No media activations stand in the store; there is nothing to serve.\n\n")
		return
	}
	tasks := make([]string, len(scope.Tasks))
	for index, task := range scope.Tasks {
		tasks[index] = string(task)
	}
	fmt.Fprintf(output, "The selected tasks (%s) have %d activations; %d are stale and %d healthy activations cite a readable measured verifier run. Measurements retain their original scope and source revision.\n\n", strings.Join(tasks, ", "), activations, stale, measured)
}

// writeMediaSurface renders the public entry points every media
// capability shares: the task-generic recipe lifecycle CLI. The rows
// restate the command contract, not per-model knowledge.
func writeMediaSurface(output *bytes.Buffer) {
	output.WriteString("## Public media surface\n\n")
	output.WriteString("Every media capability is exercised through the same task-generic recipe lifecycle; requests are typed JSON on standard input and outputs are typed store artifacts.\n\n")
	output.WriteString("| Operation | Command |\n| --- | --- |\n")
	for _, row := range [][2]string{
		{"Verify (candidate execution + gate/run evidence)", "`go run ./cmd/recipe verify -task <task> -repo <overgodb> -input - <model-path> < request.json`"},
		{"Activate (bind verified evidence to the active alias)", "`go run ./cmd/recipe activate -task <task> -repo <overgodb> -gate <id> -run-id <id> -reason <why> <model-path>`"},
		{"Run (serve through the active recipe)", "`go run ./cmd/recipe run -task <task> -repo <overgodb> -input - <model-path> < request.json`"},
		{"Report (this document)", "`go run ./cmd/compatibility -update-media`"},
		{"Sample export (recorded generation outputs)", "`go run ./cmd/compatibility -export-samples`"},
	} {
		fmt.Fprintf(output, "| %s | %s |\n", row[0], row[1])
	}
	output.WriteString("\nThe report includes only the selected tasks and the recipes actually declared by their active records. Reference-guided video editing is a `video-gen` recipe with a source input.\n\n")
}

// writeMediaInventories renders the compiled recipe graphs behind the
// healthy activations: per activation, the recipe identity and its
// node/module/placement decomposition, straight from the stored
// definitions.
func writeMediaInventories(
	output *bytes.Buffer,
	rows []reportRow,
) {
	output.WriteString("## Function inventory\n\n")
	output.WriteString("The executable surface behind each healthy activation: every recipe node with its module and placement, from the activation's own stored definition. Modules are the native Go implementations the workflow runtime binds.\n\n")
	output.WriteString("| Model | Task | Node | Module | Placement | Session | Component model |\n| --- | --- | --- | --- | --- | --- | --- |\n")
	nodes := 0
	output2 := &bytes.Buffer{}
	output2.WriteString("## Recipe inventory\n\n")
	output2.WriteString("One row per healthy activation: the recipe artifact the active alias resolves, its evidence tier, and its non-model dependencies.\n\n")
	output2.WriteString("| Model | Task | Recipe | Evidence tier | Dependencies |\n| --- | --- | --- | --- | --- |\n")
	recipes := 0
	for _, row := range rows {
		if row.stale != "" {
			continue
		}
		activation := row.activation
		for _, node := range activation.Definition.Nodes {
			session := string(node.Session)
			session = cmp.Or(session, "-")
			// A slotted node states the content-identified component model
			// it executes against; a shared component (a Flux-lineage VAE,
			// for example) renders the same identity wherever it appears.
			component := "composite"
			if node.ModelSlot != 0 {
				if model, ok := activation.Definition.Dependency(recipe.DependencyModel, node.ModelSlot); ok {
					component = "`" + shortArtifact(model) + "`"
				}
			}
			fmt.Fprintf(output, "| `%s` | `%s` | `%s` | `%s` | %s | %s | %s |\n",
				escapeMarkdown(row.model), row.task, node.ID, node.Module, node.Placement, session, component)
			nodes++
		}
		dependencies := make([]string, 0, len(activation.Definition.Dependencies))
		for _, dependency := range activation.Definition.Dependencies {
			if dependency.Role == recipe.DependencyModel {
				continue
			}
			dependencies = append(dependencies, fmt.Sprintf("%s `%s`", dependency.Role, shortArtifact(dependency.Artifact)))
		}
		rendered := "-"
		if len(dependencies) > 0 {
			rendered = strings.Join(dependencies, ", ")
		}
		fmt.Fprintf(output2, "| `%s` | `%s` | `%s` | %s | %s |\n",
			escapeMarkdown(row.model), row.task, shortArtifact(activation.Definition.ID), activation.Tier, rendered)
		recipes++
	}
	if nodes == 0 {
		output.WriteString("\nNo healthy activation stands; the inventory is empty.\n")
	}
	if recipes == 0 {
		output2.WriteString("\nNo healthy activation stands; the inventory is empty.\n")
	}
	output.WriteString("\n")
	output.Write(output2.Bytes())
	output.WriteString("\n")
}

// writeMediaSamplesSection links the exported generation outputs
// under docs/media_samples: images and clips embed inline, audio links
// as playable WAV. Only files that exist on disk are linked, and each
// is named by its content SHA-256 so it is checkable against the run
// that produced it.
func writeMediaSamplesSection(
	ctx context.Context,
	output *bytes.Buffer,
	store *overgodb.Store,
	root string,
	rows []reportRow,
) error {
	output.WriteString("\n## Samples\n\n")
	output.WriteString("Outputs from recorded successful generation runs, exported by `go run ./cmd/compatibility -export-samples` and named by content SHA-256. A successful run does not by itself establish visual quality. Use `-media-scope image-video` with sample export to select the frozen image/video requests. Repeated identical output bytes share one file; each sample cites a producing run.\n\n")
	directory := filepath.Join(root, mediaSamplesDir)
	linked := 0
	for _, row := range rows {
		if row.stale != "" {
			continue
		}
		samples, err := recipeSampleNames(ctx, store, row.activation.Definition.ID, nil)
		if err != nil {
			return err
		}
		present := make([]sampleRef, 0, len(samples))
		for _, sample := range samples {
			if sampleErr := validateMediaSampleFile(directory, sample.Name); sampleErr == nil {
				present = append(present, sample)
			} else {
				fmt.Fprintf(output, "Unavailable or invalid export `%s`: %s. Run `%s`; output `%s`.\n\n", sample.Name, escapeMarkdown(sampleErr.Error()), sample.Run, sample.Output)
			}
		}
		if len(present) == 0 {
			continue
		}
		name := row.model
		fmt.Fprintf(output, "### %s (`%s`)\n\n", escapeMarkdown(name), row.task)
		for _, sample := range present {
			relative, err := filepath.Rel(filepath.Dir(mediaReportPath), filepath.Join(mediaSamplesDir, sample.Name))
			if err != nil {
				return err
			}
			relative = filepath.ToSlash(relative)
			switch {
			case strings.HasSuffix(sample.Name, ".wav"):
				fmt.Fprintf(output, "- Audio clip: [%s](%s)\n", sample.Name, relative)
			case strings.HasSuffix(sample.Name, ".gif"):
				fmt.Fprintf(output, "- Video clip: [%s](%s)\n\n  ![%s clip](%s)\n", sample.Name, relative, escapeMarkdown(name), relative)
			default:
				fmt.Fprintf(output, "- Image: [%s](%s)\n\n  ![%s image](%s)\n", sample.Name, relative, escapeMarkdown(name), relative)
			}
			if sample.Request != "" {
				fmt.Fprintf(output, "\n  Request: `%s`\n", sample.Request)
			}
			fmt.Fprintf(output, "\n  Run: `%s`; output: `%s`. Source: %s. Environment: %s.\n", sample.Run, sample.Output, mediaEvidenceCell(sample.Commit), mediaEvidenceCell(sample.Environment.String()))
			inputs := make([]string, len(sample.Inputs))
			for index, input := range sample.Inputs {
				inputs[index] = mediaEvidenceCell(input.String())
			}
			if len(inputs) == 0 {
				inputs = append(inputs, "unavailable")
			}
			fmt.Fprintf(output, "\n  Input artifacts: %s.\n", strings.Join(inputs, ", "))
			linked++
		}
		output.WriteString("\n")
	}
	if linked == 0 {
		output.WriteString("No exported samples are present on disk; run the sample export first.\n")
	}
	return nil
}

func mediaEvidenceCell(value string) string {
	if value == "" || value == (artifact.ID{}).String() {
		return "unavailable"
	}
	return "`" + escapeMarkdown(value) + "`"
}

func shortArtifact(id artifact.ID) string {
	rendered := id.String()
	if len(rendered) > 32 {
		return rendered[:32]
	}
	return rendered
}

// Render the selected verifier, never another run found beside it.
func mediaRunResult(verified runrecord.Verification) string {
	if !verified.Run.ID.Valid() {
		return "- | - | - | - | -"
	}
	peak := "-"
	for _, step := range verified.Gate.Steps {
		if value, ok := stepPeakDeviceBytes(step.Evidence); ok {
			peak = fmt.Sprintf("%d B", value)
			break
		}
	}
	run := verified.Run
	outputs := make([]string, 0, len(run.Outputs))
	for _, output := range run.Outputs {
		outputs = append(outputs, "`"+shortArtifact(output)+"`")
	}
	return fmt.Sprintf("%s | %s | %s | `%s` | %s",
		time.Duration(run.MeasuredNS).Round(time.Millisecond).String(),
		phaseCell(run.Phases), peak, shortCommit(run.CodeCommit), cmp.Or(strings.Join(outputs, ", "), "-"))
}

// mediaRunPhases is the report's phase scope: the measured recipe-node
// decomposition, excluding the gate's own bookkeeping phases whose
// totals duplicate the wall column.
var mediaRunPhases = map[runrecord.Phase]bool{
	runrecord.PhasePrepare: true, runrecord.PhaseIntegrate: true,
	runrecord.PhaseDecode: true, runrecord.PhaseGenerate: true,
	runrecord.PhaseTokenize: true,
}

// phaseCell renders the run's recorded node-phase walls in recorded
// order, or the dash when the run predates phase capture.
func phaseCell(phases []runrecord.PhaseMetric) string {
	parts := make([]string, 0, len(phases))
	for _, metric := range phases {
		if !mediaRunPhases[metric.Phase] {
			continue
		}
		parts = append(parts, fmt.Sprintf("%s %s",
			metric.Phase, time.Duration(metric.DurationNS).Round(time.Millisecond)))
	}
	if len(parts) == 0 {
		return "-"
	}
	return strings.Join(parts, ", ")
}

// stepPeakDeviceBytes parses the peak_device_bytes evidence marker a
// measured verification writes into its execution step.
func stepPeakDeviceBytes(evidence string) (uint64, bool) {
	const marker = "peak_device_bytes="
	for field := range strings.FieldsSeq(evidence) {
		digits, found := strings.CutPrefix(field, marker)
		if !found {
			continue
		}
		if digits == "" || strings.Trim(digits, "0123456789") != "" {
			return 0, false
		}
		var value uint64
		_, err := fmt.Sscanf(digits, "%d", &value)
		return value, err == nil
	}
	return 0, false
}

// mediaModelName derives a distinctive name from a recorded location:
// the deepest path segment that is not a generic weights file or a
// standard repository component directory. The skipped names are
// format facts of the HF and diffusers layouts, not model knowledge.
func mediaModelName(location string) string {
	generic := map[string]bool{
		"text_encoder": true, "transformer": true, "vae": true,
		"scheduler": true, "tokenizer": true,
		"classification": true, "regression": true,
	}
	segments := strings.Split(filepath.ToSlash(location), "/")
	for index := len(segments) - 1; index >= 0; index-- {
		segment := segments[index]
		lower := strings.ToLower(segment)
		if strings.HasSuffix(lower, ".safetensors") || strings.HasSuffix(lower, ".gguf") ||
			strings.HasSuffix(lower, ".pt") || generic[lower] {
			continue
		}
		return segment
	}
	return filepath.Base(location)
}

func mediaTask(task recipe.Task) bool {
	return slices.Contains(mediaTasks, task)
}

func staleCell(stale string) string {
	if stale == "" {
		return "-"
	}
	return "stale: " + escapeMarkdown(stale)
}

// claimCell renders the strongest verification claim recorded for the
// capability, or the dash when none stands.
func claimCell(claims []runrecord.CapabilityClaim, task recipe.Task) string {
	for _, claim := range claims {
		if claim.Capability != string(task) {
			continue
		}
		parts := []string{string(claim.Tier)}
		if measured(claim.WallNS) {
			parts = append(parts, time.Duration(claim.WallNS).Round(time.Millisecond).String())
		}
		if measured(claim.PeakDeviceBytes) {
			parts = append(parts, fmt.Sprintf("%d B peak", claim.PeakDeviceBytes))
		}
		parts = append(parts, "`"+shortCommit(claim.Commit)+"`")
		return strings.Join(parts, ", ")
	}
	return "-"
}

func shortCommit(commit string) string {
	if len(commit) > 12 {
		return commit[:12]
	}
	return commit
}
