package main

import (
	"bytes"
	"context"
	"fmt"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"overgo/internal/artifact"
	"overgo/internal/discovery"
	"overgo/internal/overgodb"
	"overgo/internal/recipe"
	"overgo/internal/runrecord"
)

// The media report is the generated counterpart of a hand-written
// validation report: every media-task activation the store holds --
// speech, image and video generation, video edit, vision QA -- joined
// with the typed verification claims that measured it. Nothing is
// asserted the store does not record; a hand-written verdict never
// enters a generated projection.
const mediaReportPath = "docs/MEDIA_REPORT.md"

// mediaTasks are the report's scope: output-producing media
// capabilities, in ladder order.
// mediaCatalogLimit bounds the catalog read far above the local model
// population; truncation is reported in the output rather than hidden.
const mediaCatalogLimit = 4096

var mediaTasks = []recipe.Task{
	recipe.TaskSpeech, recipe.TaskImageGen, recipe.TaskVideoGen, recipe.TaskVideoEdit, recipe.TaskVQA,
}

// generateMediaReport renders every media activation with its
// verification evidence. Models without any media task are absent;
// stale activations are reported as stale, never hidden.
func generateMediaReport(root, repository string) ([]byte, error) {
	store, err := overgodb.OpenReadOnly(repository)
	if err != nil {
		return nil, err
	}
	defer store.Close()
	ctx := context.Background()
	entries, truncated, err := discovery.CapabilityCatalog(ctx, store, mediaCatalogLimit, nil)
	if err != nil {
		return nil, err
	}
	inventory, err := loadVerificationInventory(root)
	if err != nil {
		return nil, err
	}
	claimsByModel := map[artifact.ID][]runrecord.CapabilityClaim{}
	namesByModel := map[artifact.ID]string{}
	for _, row := range inventory.Rows {
		claimsByModel[row.Model] = row.Capabilities
		namesByModel[row.Model] = row.Name
	}
	var output bytes.Buffer
	output.WriteString("# Media capability report\n\n")
	output.WriteString("Generated by `go run ./cmd/compatibility -update-media` from the OvergoDB store and the typed verification specifications under `docs/verification`. Do not edit this file directly.\n\n")
	output.WriteString("Evidence rules: an activation states its recipe evidence tier; a measured claim states its verification tier, commit, and measurements; a stale activation is reported as stale, never served, never hidden. Absence of a claim row means no measured verification stands for that task.\n\n")
	output.WriteString("## Media activations\n\n")
	output.WriteString("| Model | Task | Activation tier | Stale | Measured claim |\n| --- | --- | --- | --- | --- |\n")
	type reportRow struct{ model, task, tier, stale, claim string }
	var report []reportRow
	for _, entry := range entries {
		for _, capability := range entry.Capabilities {
			if !mediaTask(capability.Task) {
				continue
			}
			name := namesByModel[entry.Model]
			if name == "" && entry.Location != "" {
				name = filepath.Base(entry.Location)
			}
			if name == "" {
				name = entry.Model.String()
			}
			report = append(report, reportRow{
				model: name, task: string(capability.Task), tier: string(capability.Tier),
				stale: staleCell(capability.Stale),
				claim: claimCell(claimsByModel[entry.Model], capability.Task),
			})
		}
	}
	sort.Slice(report, func(i, j int) bool {
		if report[i].model != report[j].model {
			return report[i].model < report[j].model
		}
		return report[i].task < report[j].task
	})
	for _, row := range report {
		fmt.Fprintf(&output, "| `%s` | `%s` | %s | %s | %s |\n",
			escapeMarkdown(row.model), row.task, row.tier, row.stale, row.claim)
	}
	if len(report) == 0 {
		output.WriteString("\nNo media activations stand in the store.\n")
	}
	if truncated {
		output.WriteString("\nThe capability listing was truncated; this report is incomplete and says so.\n")
	}
	output.WriteString("\nThe matrix reports activation and evidence scope, not general model-family support: an activation means the recipe lifecycle admitted the model for the task at the stated tier, and a measured claim binds that capability to real execution evidence at its commit.\n")
	return output.Bytes(), nil
}

func mediaTask(task recipe.Task) bool {
	for _, candidate := range mediaTasks {
		if candidate == task {
			return true
		}
	}
	return false
}

func staleCell(stale string) string {
	if stale == "" {
		return "-"
	}
	return "stale: " + escapeMarkdown(stale)
}

// claimCell renders the strongest verification claim recorded for the
// capability, or the honest dash when none stands.
func claimCell(claims []runrecord.CapabilityClaim, task recipe.Task) string {
	for _, claim := range claims {
		if claim.Capability != string(task) {
			continue
		}
		parts := []string{string(claim.Tier)}
		if measured(claim.WallNS) {
			parts = append(parts, time.Duration(claim.WallNS).Round(time.Millisecond).String())
		}
		if measured(claim.PeakDeviceBytes) {
			parts = append(parts, fmt.Sprintf("%d B peak", claim.PeakDeviceBytes))
		}
		parts = append(parts, "`"+shortCommit(claim.Commit)+"`")
		return strings.Join(parts, ", ")
	}
	return "-"
}

func shortCommit(commit string) string {
	if len(commit) > 12 {
		return commit[:12]
	}
	return commit
}
