package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"time"

	"overgo/internal/artifact"
	"overgo/internal/jsonfile"
	"overgo/internal/runrecord"
)

const (
	trainingMatrixPath           = "docs/TRAINING_COMPATIBILITY.md"
	trainingSpecificationPattern = "docs/verification/*training.json"
)

type trainingSpecification struct {
	Model         artifact.ID                 `json:"model"`
	Name          string                      `json:"name"`
	Supersedes    []artifact.ID               `json:"supersedes,omitempty"`
	ModelFile     string                      `json:"model_file,omitempty"`
	EvidenceFiles []string                    `json:"evidence_files,omitempty"`
	DatasetFiles  []string                    `json:"dataset_files,omitempty"`
	Claims        []runrecord.CapabilityClaim `json:"claims"`
}

type trainingVerification struct {
	Record runrecord.ModelVerification
}

func generateTraining(root string) ([]byte, error) {
	verifications, err := loadTrainingVerifications(root)
	if err != nil {
		return nil, err
	}
	records := make([]runrecord.ModelVerification, len(verifications))
	for index, verification := range verifications {
		records[index] = verification.Record
	}
	rows := runrecord.VerificationMatrix(records)
	var output bytes.Buffer
	output.WriteString("# Training compatibility\n\n")
	output.WriteString("Generated from the typed training specifications under [`docs/verification`](verification). Do not edit this file directly.\n\n")
	fmt.Fprintf(&output, "%d model artifacts, %d strongest training claims.\n\n", len(rows), trainingClaimCount(rows))
	output.WriteString("| Model | Capability | Tier | Span | Wall | Peak device | Commit |\n")
	output.WriteString("| --- | --- | --- | ---: | ---: | ---: | --- |\n")
	for _, row := range rows {
		for _, claim := range row.Capabilities {
			if !trainingCapability(claim.Capability) {
				continue
			}
			span := trainingSpan(claim)
			wall := "-"
			if measured(claim.WallNS) {
				wall = time.Duration(claim.WallNS).Round(time.Millisecond).String()
			}
			peak := "-"
			if measured(claim.PeakDeviceBytes) {
				peak = fmt.Sprintf("%d B", claim.PeakDeviceBytes)
			}
			fmt.Fprintf(&output, "| `%s` | `%s` | `%s` | %s | %s | %s | `%s` |\n",
				escapeMarkdown(row.Name), claim.Capability, claim.Tier, span, wall, peak, claim.Commit)
		}
	}
	output.WriteString("\nThe matrix reports evidence scope, not general model-family support. `real-artifact-smoke` establishes the named bounded run; it does not imply convergence, a complete training campaign, or production promotion.\n")
	return output.Bytes(), nil
}

func loadTrainingVerifications(root string) ([]trainingVerification, error) {
	paths, err := filepath.Glob(filepath.Join(root, filepath.FromSlash(trainingSpecificationPattern)))
	if err != nil {
		return nil, err
	}
	if len(paths) == len([]string(nil)) {
		return nil, errors.New("training compatibility: no verification specifications")
	}
	sort.Strings(paths)
	result := make([]trainingVerification, len(paths))
	for index, path := range paths {
		var specification trainingSpecification
		if err := jsonfile.Decode(path, &specification); err != nil {
			return nil, fmt.Errorf("training compatibility: %s: %w", filepath.ToSlash(path), err)
		}
		record, err := runrecord.NewModelVerificationCorrection(
			specification.Model, specification.Name, specification.Claims, specification.Supersedes,
		)
		if err != nil {
			return nil, fmt.Errorf("training compatibility: %s: %w", filepath.ToSlash(path), err)
		}
		if err := validateTrainingSpecification(root, specification, record); err != nil {
			return nil, fmt.Errorf("training compatibility: %s: %w", filepath.ToSlash(path), err)
		}
		result[index] = trainingVerification{Record: record}
	}
	return result, nil
}

func validateTrainingSpecification(root string, specification trainingSpecification, record runrecord.ModelVerification) error {
	claimedEvidence := make(map[artifact.ID]bool)
	claimedDatasets := make(map[artifact.ID]bool)
	for _, claim := range record.Claims {
		if !trainingCapability(claim.Capability) {
			return fmt.Errorf("capability %q is not a training claim", claim.Capability)
		}
		if !measured(claim.SpanSteps) && !measured(claim.SpanTokens) {
			return fmt.Errorf("capability %q has no observed span", claim.Capability)
		}
		if err := requireCommit(root, claim.Commit); err != nil {
			return fmt.Errorf("capability %q: %w", claim.Capability, err)
		}
		claimedDatasets[claim.Dataset] = true
		for _, evidence := range claim.Evidence {
			claimedEvidence[evidence] = true
		}
	}
	localEvidence, err := referencedFileIDs(root, specification.EvidenceFiles, artifact.KindEvidence, claimedEvidence, false)
	if err != nil {
		return fmt.Errorf("evidence files: %w", err)
	}
	if len(localEvidence) == len(map[artifact.ID]bool(nil)) {
		return errors.New("no local evidence file")
	}
	for _, claim := range record.Claims {
		if !slices.ContainsFunc(claim.Evidence, func(id artifact.ID) bool { return localEvidence[id] }) {
			return fmt.Errorf("capability %q has no locally grounded evidence", claim.Capability)
		}
	}
	if _, err := referencedFileIDs(root, specification.DatasetFiles, artifact.KindDatasetShard, claimedDatasets, true); err != nil {
		return fmt.Errorf("dataset files: %w", err)
	}
	return nil
}

func referencedFileIDs(root string, paths []string, kind artifact.Kind, claimed map[artifact.ID]bool, allowExternal bool) (map[artifact.ID]bool, error) {
	result := make(map[artifact.ID]bool, len(paths))
	seen := make(map[string]bool, len(paths))
	for _, path := range paths {
		if allowExternal && filepath.IsAbs(path) {
			continue
		}
		full, err := repositoryFile(root, path)
		if err != nil {
			return nil, err
		}
		if seen[full] {
			return nil, fmt.Errorf("duplicate path %s", path)
		}
		seen[full] = true
		data, err := os.ReadFile(full)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		id, err := artifact.IdentifyBytes(kind, data)
		if err != nil {
			return nil, err
		}
		if !claimed[id] {
			return nil, fmt.Errorf("%s identifies as unclaimed %s", path, id)
		}
		if result[id] {
			return nil, fmt.Errorf("duplicate identity %s", id)
		}
		result[id] = true
	}
	return result, nil
}

func repositoryFile(root, path string) (string, error) {
	if path == "" || filepath.IsAbs(path) {
		return "", fmt.Errorf("invalid repository path %q", path)
	}
	root, err := filepath.Abs(root)
	if err != nil {
		return "", err
	}
	full, err := filepath.Abs(filepath.Join(root, filepath.FromSlash(path)))
	if err != nil {
		return "", err
	}
	relative, err := filepath.Rel(root, full)
	if err != nil || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("path escapes repository: %q", path)
	}
	return full, nil
}

func requireCommit(root, commit string) error {
	command := exec.Command("git", "-C", root, "cat-file", "-e", commit+"^{commit}")
	if output, err := command.CombinedOutput(); err != nil {
		return fmt.Errorf("commit %s is unavailable: %w: %s", commit, err, strings.TrimSpace(string(output)))
	}
	return nil
}

func trainingClaimCount(rows []runrecord.MatrixRow) int {
	var count int
	for _, row := range rows {
		for _, claim := range row.Capabilities {
			if trainingCapability(claim.Capability) {
				count++
			}
		}
	}
	return count
}

func trainingCapability(capability string) bool {
	return capability == "training" || strings.HasSuffix(capability, "-training")
}

func trainingSpan(claim runrecord.CapabilityClaim) string {
	span := fmt.Sprintf("%d steps", claim.SpanSteps)
	if measured(claim.SpanTokens) {
		span += fmt.Sprintf(" / %d tokens", claim.SpanTokens)
	}
	return span
}

func measured(value uint64) bool {
	var absent uint64
	return value != absent
}

func escapeMarkdown(value string) string { return strings.ReplaceAll(value, "|", "\\|") }
