package gate

import (
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"
	"testing"

	"overgo/internal/automationcheck"
	"overgo/internal/codemanifest"
	"overgo/internal/repoanalysis"
)

func TestManifestFalseNegativeCorpus(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name, base, candidate string
		kind                  codemanifest.UncertaintyKind
		selected              bool
		external              bool
	}{
		{
			name: "interface dispatch", kind: codemanifest.UncertaintyInterface, selected: true,
			base:      "package example\ntype Runner interface { Run() int }\ntype Worker struct{}\nfunc (Worker) Run() int { return 1 }\nfunc invoke(value Runner) int { return value.Run() }\n",
			candidate: "package example\ntype Runner interface { Run() int }\ntype Worker struct{}\nfunc (Worker) Run() int { return 2 }\nfunc invoke(value Runner) int { return value.Run() }\n",
		},
		{
			name: "reflection", kind: codemanifest.UncertaintyReflection, selected: true,
			base:      "package example\ntype Worker struct{}\nfunc (Worker) Run() int { return 1 }\nfunc inspect(value Worker) { value.MethodByName(\"Run\") }\n",
			candidate: "package example\ntype Worker struct{}\nfunc (Worker) Run() int { return 2 }\nfunc inspect(value Worker) { value.MethodByName(\"Run\") }\n",
		},
		{
			name: "cgo export", kind: codemanifest.UncertaintyCgo, selected: true,
			base:      "package example\n//export CRun\nfunc CRun() int { return 1 }\n",
			candidate: "package example\n//export CRun\nfunc CRun() int { return 2 }\n",
		},
		{
			name: "generated source", kind: codemanifest.UncertaintyGenerated, selected: true,
			base:      "// Code generated by fixture. DO NOT EDIT.\npackage example\nfunc Generated() int { return 1 }\n",
			candidate: "// Code generated by fixture. DO NOT EDIT.\npackage example\nfunc Generated() int { return 2 }\n",
		},
		{
			name: "build tag variant", kind: codemanifest.UncertaintyBuildSelection,
			base:      "//go:build windows\npackage example\nfunc Variant() int { return 1 }\n",
			candidate: "//go:build windows\npackage example\nfunc Variant() int { return 2 }\n",
		},
		{
			name: "non-Go input", kind: codemanifest.UncertaintyNonGo, selected: true, external: true,
			base:      "package example\nfunc Stable() int { return 1 }\n",
			candidate: "package example\nfunc Stable() int { return 1 }\n",
		},
	}
	checks := []automationcheck.Check{
		bootstrapCheck("model", "owner:model"), bootstrapCheck("device", "owner:device"), bootstrapCheck("schema", "owner:schema"),
	}
	for _, fixture := range cases {
		t.Run(fixture.name, func(t *testing.T) {
			impact := deriveBoundaryImpact(t, fixture.base, fixture.candidate, fixture.selected, fixture.external)
			if !manifestImpactHasBoundary(impact, fixture.kind) {
				t.Fatalf("derived impact lacks %q boundary: %+v", fixture.kind, impact)
			}
			surface := automationcheck.ManifestSurface(impact)
			verdict := automationcheck.OwnershipImpact(checks, surface)
			planned, err := automationcheck.Plan(checks, verdict)
			if err != nil || len(planned) != len(checks) || len(verdict.Exclusions) != 0 {
				t.Fatalf("boundary under-selected checks: planned=%d/%d impact=%+v err=%v", len(planned), len(checks), verdict, err)
			}
		})
	}
}

func deriveBoundaryImpact(t *testing.T, baseSource, candidateSource string, selected, external bool) codemanifest.Impact {
	t.Helper()
	root := t.TempDir()
	const sourcePath = "internal/example/example.go"
	abs := filepath.Join(root, filepath.FromSlash(sourcePath))
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(abs, []byte(baseSource), 0o600); err != nil {
		t.Fatal(err)
	}
	baseSnapshot, err := repoanalysis.DiscoverGo(root, "internal")
	if err != nil {
		t.Fatal(err)
	}
	candidateSnapshot, err := baseSnapshot.Overlay(map[string][]byte{sourcePath: []byte(candidateSource)})
	if err != nil {
		t.Fatal(err)
	}
	selection := repoanalysis.BuildSelection{
		Context: "linux/amd64", Root: root,
		Files: map[string]bool{sourcePath: selected}, Packages: map[string]string{sourcePath: "overgo/internal/example"},
	}
	var baseInputs, candidateInputs []codemanifest.ExternalInput
	if external {
		baseInputs = []codemanifest.ExternalInput{{Path: "kernels/example.cu", ContentID: boundaryDigest("a"), Kind: "cuda-source", Owner: "internal/cuda"}}
		candidateInputs = []codemanifest.ExternalInput{{Path: "kernels/example.cu", ContentID: boundaryDigest("b"), Kind: "cuda-source", Owner: "internal/cuda"}}
	}
	baseManifest, err := codemanifest.Generate(baseSnapshot, []repoanalysis.BuildSelection{selection}, baseInputs)
	if err != nil {
		t.Fatal(err)
	}
	candidateManifest, err := codemanifest.Generate(candidateSnapshot, []repoanalysis.BuildSelection{selection}, candidateInputs)
	if err != nil {
		t.Fatal(err)
	}
	delta, err := codemanifest.Diff(baseManifest, candidateManifest)
	if err != nil {
		t.Fatal(err)
	}
	impact, err := codemanifest.Close(baseManifest, candidateManifest, delta)
	if err != nil {
		t.Fatal(err)
	}
	return impact
}

func manifestImpactHasBoundary(impact codemanifest.Impact, kind codemanifest.UncertaintyKind) bool {
	for _, boundary := range impact.Uncertainty {
		if boundary.Kind == kind {
			return true
		}
	}
	return false
}

func boundaryDigest(seed string) string {
	digest := sha256.Sum256([]byte(seed))
	return hex.EncodeToString(digest[:])
}
