package gostyle

import (
	"encoding/json"
	"runtime"
	"strings"
	"testing"

	"overgo/internal/repoanalysis"
	"overgo/internal/testutil"
)

func TestGoStylePolicyAndBaseline(t *testing.T) {
	base := sourceSnapshot(t, map[string]string{
		"sample/good.go":      "package sample\ntype Consumer interface { Use() }\n",
		"sample/generated.go": "// Code generated by policy_test; DO NOT EDIT.\npackage Bad_Name\nvar bad_global int\n",
	})
	candidate, err := base.Overlay(map[string][]byte{
		"sample/good.go": []byte("package sample\nimport er \"errors\"\nfunc f() error { return er.New(\"Bad.\") }\n"),
	})
	if err != nil {
		t.Fatal(err)
	}
	report, err := Compare(base, candidate)
	if err != nil {
		t.Fatal(err)
	}
	if report.Base.Identity == "" || report.Base.Identity == report.Candidate.Identity {
		t.Fatal("comparison is not bound to distinct source identities")
	}
	if len(report.Rules) != len(Policy()) || len(report.Base.Exclusions) != 1 {
		t.Fatalf("incomplete policy or exclusions: rules=%d exclusions=%+v", len(report.Rules), report.Base.Exclusions)
	}
	assertRuleChange(t, report, "interface-ownership", Resolved)
	assertRuleChange(t, report, "errors", Introduced)
}

func TestGoReadabilityCandidateDelta(t *testing.T) {
	t.Run("maturity provenance and normalized report", func(t *testing.T) {
		if err := validatePolicy(); err != nil {
			t.Fatal(err)
		}
		for _, rule := range Policy() {
			if rule.SourceID == "" || rule.SourceSection == "" || reviewedSources[rule.SourceID] != rule.SourceSection {
				t.Fatalf("rule has unreviewed source: %+v", rule)
			}
			if rule.Maturity == Enforceable {
				t.Fatalf("first gate revision prematurely enforces %s", rule.ID)
			}
		}
		report, err := Compare(sourceSnapshot(t, map[string]string{"p/p.go": "package p\n"}), sourceSnapshot(t, map[string]string{"p/p.go": "package p\nvar value int\n"}))
		if err != nil {
			t.Fatal(err)
		}
		encoded, err := json.Marshal(report)
		if err != nil {
			t.Fatal(err)
		}
		text := string(encoded)
		if strings.Contains(text, `"score"`) || strings.Contains(text, `"diagnostic":{"rule_id"`) || strings.Contains(text, `"diagnostic":{"tier"`) {
			t.Fatalf("report contains a score or repeated rule metadata: %s", text)
		}
	})

	t.Run("aliases shadowing and declaration scope", func(t *testing.T) {
		base := sourceSnapshot(t, map[string]string{"p/p.go": "package p\n"})
		candidate := sourceSnapshot(t, map[string]string{"p/p.go": `package p
import (
	cx "context"
	er "errors"
)
type record_value struct { field_name int }
type errorFactory struct{}
func (errorFactory) New(string) error { return nil }
func check_value(input_value int, ctx cx.Context) error {
	errors := errorFactory{}
	_ = errors.New("Shadowed.")
	return er.New("Imported.")
}
`})
		report, err := Compare(base, candidate)
		if err != nil {
			t.Fatal(err)
		}
		if got := introducedCount(report, "errors"); got != 1 {
			t.Fatalf("import-resolved error diagnostics = %d, want 1", got)
		}
		if got := introducedCount(report, "context"); got != 1 {
			t.Fatalf("aliased context diagnostics = %d, want 1", got)
		}
		if got := introducedCount(report, "mixed-caps"); got < 4 {
			t.Fatalf("declaration-scope MixedCaps diagnostics = %d, want fields, parameters, locals, and declarations", got)
		}
	})

	t.Run("receiver identity and line movement", func(t *testing.T) {
		base := sourceSnapshot(t, map[string]string{"p/p.go": `package p
type T struct{}
func (t T) M() { _ = t }
`})
		candidate := sourceSnapshot(t, map[string]string{"p/p.go": `package p

type T struct{}

func (t T) M() {
	func(t int) { _ = t }(1)
}
`})
		report, err := Compare(base, candidate)
		if err != nil {
			t.Fatal(err)
		}
		assertRuleChange(t, report, "receivers", Introduced)
		stableBase := sourceSnapshot(t, map[string]string{"p/p.go": "package p\nimport \"errors\"\nfunc f() error { return errors.New(\"Bad.\") }\n"})
		stableCandidate := sourceSnapshot(t, map[string]string{"p/p.go": "package p\n\nimport \"errors\"\n\nfunc f() error { return errors.New(\"Bad.\") }\n"})
		stable, err := Compare(stableBase, stableCandidate)
		if err != nil {
			t.Fatal(err)
		}
		if introducedCount(stable, "errors") != 0 {
			t.Fatal("line-only movement produced a rule regression")
		}
	})

	t.Run("host build context", func(t *testing.T) {
		root := t.TempDir()
		testutil.WriteTextFile(t, root, "go.mod", "module fixture\n\ngo 1.26\n")
		testutil.WriteTextFile(t, root, "p/p.go", "package p\n")
		testutil.WriteTextFile(t, root, "p/p_windows.go", "package p\nvar windows_name int\n")
		testutil.WriteTextFile(t, root, "p/p_linux.go", "package p\nvar linux_name int\n")
		testutil.WriteTextFile(t, root, "p/tagged.go", "// +build nevermatch\n\npackage p\nvar tagged_name int\n")
		testutil.WriteTextFile(t, root, "p/legacy.go", "// +build "+runtime.GOOS+"\n\npackage p\n")
		selection, err := repoanalysis.HostBuildSelection(root, "./...")
		if err != nil {
			t.Fatal(err)
		}
		wantSelected, wantExcluded := "p/p_"+runtime.GOOS+".go", "p/p_linux.go"
		if runtime.GOOS == "linux" {
			wantExcluded = "p/p_windows.go"
		}
		if selected, known := selection.Files[wantSelected]; !known || !selected {
			t.Fatalf("host file %s selection = %t, %t", wantSelected, selected, known)
		}
		if selected, known := selection.Files[wantExcluded]; !known || selected {
			t.Fatalf("foreign file %s selection = %t, %t", wantExcluded, selected, known)
		}
		snapshot, err := repoanalysis.DiscoverGo(root, "p")
		if err != nil {
			t.Fatal(err)
		}
		census, err := Census(snapshot, Options{Build: selection})
		if err != nil {
			t.Fatal(err)
		}
		if len(census.Exclusions) < 2 || census.BuildContext == "" {
			t.Fatalf("build evidence = context %q exclusions %+v", census.BuildContext, census.Exclusions)
		}
		legacyRecorded := false
		for _, constraint := range census.BuildConstraints {
			legacyRecorded = legacyRecorded || constraint.File == "p/legacy.go" && constraint.Selected
		}
		if !legacyRecorded {
			t.Fatalf("legacy selected constraint absent: %+v", census.BuildConstraints)
		}
		for _, result := range census.Rules {
			for _, diagnostic := range result.Diagnostics {
				if diagnostic.File == wantExcluded || diagnostic.File == "p/tagged.go" {
					t.Fatalf("excluded build variant produced a diagnostic: %+v", diagnostic)
				}
			}
		}
	})

	t.Run("unchanged facts are reused", func(t *testing.T) {
		base := sourceSnapshot(t, map[string]string{
			"p/a.go": "package p\nfunc a() {}\n",
			"p/b.go": "package p\nfunc b() {}\n",
		})
		candidate, err := base.Overlay(map[string][]byte{"p/a.go": []byte("package p\nfunc a() { panic(\"changed\") }\n")})
		if err != nil {
			t.Fatal(err)
		}
		report, err := Compare(base, candidate)
		if err != nil {
			t.Fatal(err)
		}
		if report.Analysis.FilesReused != 1 || report.Analysis.FilesScanned != 3 || report.Analysis.SyntaxPasses != 3 {
			t.Fatalf("analysis reuse = %+v", report.Analysis)
		}
	})
}

func sourceSnapshot(t *testing.T, files map[string]string) repoanalysis.SourceSnapshot {
	t.Helper()
	contents := make(map[string][]byte, len(files))
	for name, content := range files {
		contents[name] = []byte(content)
	}
	snapshot, err := (repoanalysis.SourceSnapshot{}).Overlay(contents)
	if err != nil {
		t.Fatal(err)
	}
	return snapshot
}

func introducedCount(report BaselineReport, ruleID string) int {
	for _, delta := range report.Rules {
		if delta.Rule.ID == ruleID {
			count := 0
			for _, change := range delta.Changes {
				if change.State == Introduced {
					count++
				}
			}
			return count
		}
	}
	return 0
}

func assertRuleChange(t *testing.T, report BaselineReport, ruleID string, state DeltaState) {
	t.Helper()
	for _, delta := range report.Rules {
		if delta.Rule.ID != ruleID {
			continue
		}
		for _, change := range delta.Changes {
			if change.State == state {
				return
			}
		}
		t.Fatalf("rule %s has no %s change: %+v", ruleID, state, delta)
	}
	t.Fatalf("rule %s was not reported", ruleID)
}
