package gostyle

import (
	"encoding/json"
	"path/filepath"
	"runtime"
	"testing"

	"overgo/internal/repoanalysis"
)

func TestGoStylePolicyAndBaseline(t *testing.T) {
	t.Run("catalog and candidate baseline", func(t *testing.T) {
		base, err := (repoanalysis.SourceSnapshot{}).Overlay(map[string][]byte{
			"sample/good.go": []byte(`package sample
import "context"
type Consumer interface { Use() }
type thing struct{}
func (t thing) Run(ctx context.Context) error { return nil }
`),
			"sample/constrained.go": []byte(`//go:build linux

package sample
`),
			"sample/generated.go": []byte(`// Code generated by policy_test; DO NOT EDIT.
package Bad_Name
var bad_global int
`),
		})
		if err != nil {
			t.Fatal(err)
		}
		candidate, err := base.Overlay(map[string][]byte{
			"sample/good.go": []byte(`package sample
import (
	"context"
	"errors"
)
type thing struct{}
func (t thing) Run(value int, ctx context.Context) (error, int) {
	return errors.New("Bad."), 0
}
`),
		})
		if err != nil {
			t.Fatal(err)
		}
		report, err := Compare(base, candidate)
		if err != nil {
			t.Fatal(err)
		}
		if report.BaseIdentity == "" || report.BaseIdentity == report.CandidateIdentity {
			t.Fatalf("unbound identities: base=%q candidate=%q", report.BaseIdentity, report.CandidateIdentity)
		}
		if len(report.Rules) != len(Policy()) {
			t.Fatalf("reported %d of %d policy rules", len(report.Rules), len(Policy()))
		}
		seen := map[string]bool{}
		for _, delta := range report.Rules {
			if seen[delta.Rule.ID] || delta.Rule.SourceSection == "" || delta.Rule.Tier == "" {
				t.Fatalf("rule has duplicate identity or lacks provenance: %+v", delta.Rule)
			}
			seen[delta.Rule.ID] = true
			if !delta.Available && delta.SkipReason == "" {
				t.Fatalf("rule %s was silently skipped", delta.Rule.ID)
			}
		}
		if len(report.BaseExclusions) != 1 || report.BaseExclusions[0].File != "sample/generated.go" {
			t.Fatalf("generated exclusions = %+v", report.BaseExclusions)
		}
		if len(report.BaseBuildConstraints) != 1 || report.BaseBuildConstraints[0].Expression != "linux" {
			t.Fatalf("build constraints = %+v", report.BaseBuildConstraints)
		}
		assertRuleChange(t, report, "interface-ownership", Resolved)
		assertRuleChange(t, report, "errors", Introduced)
		assertRuleChange(t, report, "context", Introduced)
		encoded, err := json.Marshal(report)
		if err != nil {
			t.Fatal(err)
		}
		var shape map[string]any
		if err := json.Unmarshal(encoded, &shape); err != nil {
			t.Fatal(err)
		}
		if _, found := shape["score"]; found {
			t.Fatal("baseline exposed an aggregate score")
		}
	})

	t.Run("line movement is not a regression", func(t *testing.T) {
		base, err := (repoanalysis.SourceSnapshot{}).Overlay(map[string][]byte{
			"p/p.go": []byte("package p\nimport \"errors\"\nfunc f() error { return errors.New(\"Bad.\") }\n"),
		})
		if err != nil {
			t.Fatal(err)
		}
		candidate, err := base.Overlay(map[string][]byte{
			"p/p.go": []byte("package p\n\nimport \"errors\"\n\nfunc f() error { return errors.New(\"Bad.\") }\n"),
		})
		if err != nil {
			t.Fatal(err)
		}
		report, err := Compare(base, candidate)
		if err != nil {
			t.Fatal(err)
		}
		for _, delta := range report.Rules {
			if delta.Rule.ID == "errors" && len(delta.Changes) != 0 {
				t.Fatalf("line-only movement produced changes: %+v", delta.Changes)
			}
		}
	})

	t.Run("repository census", func(t *testing.T) {
		_, filename, _, ok := runtime.Caller(0)
		if !ok {
			t.Fatal("cannot locate repository")
		}
		root := filepath.Clean(filepath.Join(filepath.Dir(filename), "..", ".."))
		snapshot, err := repoanalysis.DiscoverGo(root, "cmd", "internal")
		if err != nil {
			t.Fatal(err)
		}
		census, err := Census(snapshot)
		if err != nil {
			t.Fatal(err)
		}
		if census.Identity != snapshot.Identity() || len(census.Rules) != len(Policy()) {
			t.Fatal("repository census is not bound to the complete policy and snapshot")
		}
		for _, result := range census.Rules {
			if !result.Available && result.SkipReason == "" {
				t.Fatalf("rule %s was silently skipped", result.Rule.ID)
			}
			t.Logf("rule=%s mechanism=%s available=%t diagnostics=%d skip=%q", result.Rule.ID, result.Rule.Mechanism, result.Available, len(result.Diagnostics), result.SkipReason)
		}
		t.Logf("identity=%s files=%d exclusions=%d build_constraints=%d", census.Identity, len(snapshot.Files), len(census.Exclusions), len(census.BuildConstraints))
	})
}

func assertRuleChange(t *testing.T, report BaselineReport, ruleID string, state DeltaState) {
	t.Helper()
	for _, delta := range report.Rules {
		if delta.Rule.ID != ruleID {
			continue
		}
		for _, change := range delta.Changes {
			if change.State == state {
				return
			}
		}
		t.Fatalf("rule %s has no %s change: %+v", ruleID, state, delta)
	}
	t.Fatalf("rule %s was not reported", ruleID)
}
